"""
Reference tender seed data — provides fallback content for the Live Tenders panel
when TED/OCP API ingestion fails or is unavailable.
"""

from sqlalchemy.orm import Session
from app.models.tender import Tender

SEED_TENDERS = [
    {
        "source": "Reference",
        "tender_id": "ref-ca-it-001",
        "title": "Enterprise Cloud Migration and Managed Services",
        "description": "The Contractor shall deliver enterprise cloud migration services including assessment, planning, execution, and managed services for the migration of 150+ applications to a Government of Canada approved cloud environment. All data shall reside within Canadian data centres. The Contractor shall provide 24/7 managed services with 99.9% availability SLA, disaster recovery, and security monitoring in compliance with ITSG-33 and the GC Cloud Guardrails.",
        "buyer": "Shared Services Canada",
        "value": 15000000,
        "currency": "CAD",
        "country": "CA",
        "cpv_code": "72000000",
        "source_url": "https://buyandsell.gc.ca",
    },
    {
        "source": "Reference",
        "tender_id": "ref-ca-it-002",
        "title": "Cybersecurity Assessment and Penetration Testing Services",
        "description": "Provision of cybersecurity assessment services including vulnerability scanning, penetration testing, red team exercises, and security posture reviews for critical government infrastructure. The Contractor shall hold minimum Secret clearance and comply with CCCS standards. Deliverables include risk assessment reports, remediation roadmaps, and executive briefings.",
        "buyer": "Canadian Centre for Cyber Security",
        "value": 2500000,
        "currency": "CAD",
        "country": "CA",
        "cpv_code": "72212000",
        "source_url": "https://buyandsell.gc.ca",
    },
    {
        "source": "Reference",
        "tender_id": "ref-ca-con-001",
        "title": "Federal Office Building Renovation — Phases 2 and 3",
        "description": "Design-build renovation of a 25,000 sqm federal office building including structural reinforcement, HVAC modernization, accessibility upgrades to meet AODA and CSA B651 standards, fire protection system replacement, and interior fit-up. The Contractor shall obtain all permits, provide performance and labour bonds at 50%, and achieve LEED Gold certification. Substantial completion within 18 months.",
        "buyer": "Public Services and Procurement Canada",
        "value": 42000000,
        "currency": "CAD",
        "country": "CA",
        "cpv_code": "45000000",
        "source_url": "https://buyandsell.gc.ca",
    },
    {
        "source": "Reference",
        "tender_id": "ref-ca-con-002",
        "title": "Highway 401 Bridge Rehabilitation Program",
        "description": "Rehabilitation of six highway bridge structures including deck replacement, bearing replacement, substructure repairs, waterproofing membrane installation, and approach slab reconstruction. Work must comply with Ontario Provincial Standards and the Canadian Highway Bridge Design Code CSA S6. Traffic management plans required for all phases with minimum two lanes maintained during peak hours.",
        "buyer": "Ontario Ministry of Transportation",
        "value": 28000000,
        "currency": "CAD",
        "country": "CA",
        "cpv_code": "45221100",
        "source_url": "https://www.ontario.ca/page/procurement",
    },
    {
        "source": "Reference",
        "tender_id": "ref-ca-consult-001",
        "title": "Strategic Policy Advisory Services — Digital Government",
        "description": "Provision of strategic advisory services to support the Government of Canada's digital transformation agenda including policy analysis, jurisdictional benchmarking, stakeholder consultations, and development of a Digital Service Standard. The Contractor shall provide bilingual senior consultants with minimum 10 years experience in public sector digital transformation. Deliverables include a final strategy report and implementation roadmap.",
        "buyer": "Treasury Board of Canada Secretariat",
        "value": 1800000,
        "currency": "CAD",
        "country": "CA",
        "cpv_code": "79411000",
        "source_url": "https://buyandsell.gc.ca",
    },
    {
        "source": "Reference",
        "tender_id": "ref-ca-health-001",
        "title": "Electronic Health Records System Implementation",
        "description": "Implementation of an enterprise electronic health records (EHR) system across 12 hospital sites including requirements analysis, system configuration, data migration from legacy systems, HL7 FHIR integration, user training, and 24-month post-implementation support. The system shall comply with PIPEDA, Ontario PHIPA, and Canada Health Infoway standards. Interoperability with existing pharmacy, laboratory, and radiology systems is mandatory.",
        "buyer": "Ontario Health",
        "value": 35000000,
        "currency": "CAD",
        "country": "CA",
        "cpv_code": "48814000",
        "source_url": "https://www.ontario.ca/page/procurement",
    },
    {
        "source": "Reference",
        "tender_id": "ref-ca-defence-001",
        "title": "Maritime Surveillance Radar System Upgrade",
        "description": "Supply, installation, integration, and commissioning of upgraded maritime surveillance radar systems at four coastal defence installations. The system shall provide 360-degree coverage with minimum 200 nautical mile range, automatic vessel tracking, AIS integration, and secure encrypted communications. All personnel require minimum Secret security clearance. The Contractor shall provide 10 years of in-service support.",
        "buyer": "Department of National Defence",
        "value": 48000000,
        "currency": "CAD",
        "country": "CA",
        "cpv_code": "35711000",
        "source_url": "https://buyandsell.gc.ca",
    },
    {
        "source": "Reference",
        "tender_id": "ref-ca-transport-001",
        "title": "Intelligent Transportation System — Traffic Management Centre",
        "description": "Design, build, and operate an Intelligent Transportation System (ITS) including a centralized traffic management centre, 200+ CCTV cameras, variable message signs, vehicle detection sensors, and integration with existing SCADA systems. The system shall support real-time traffic monitoring, incident detection, and traveller information services. Five-year operations and maintenance contract included.",
        "buyer": "City of Toronto",
        "value": 22000000,
        "currency": "CAD",
        "country": "CA",
        "cpv_code": "34970000",
        "source_url": "https://www.toronto.ca/business-economy/doing-business-with-the-city/",
    },
    {
        "source": "Reference",
        "tender_id": "ref-ca-env-001",
        "title": "Environmental Remediation — Former Industrial Site",
        "description": "Full environmental remediation of a 15-hectare former industrial site including Phase II Environmental Site Assessment, soil excavation and treatment, groundwater monitoring and remediation, risk assessment under Ontario Regulation 153/04, and filing of a Record of Site Condition. The Contractor shall comply with the Environmental Protection Act, RSO 1990, c E-19 and obtain all necessary environmental compliance approvals.",
        "buyer": "Ontario Ministry of Environment",
        "value": 8500000,
        "currency": "CAD",
        "country": "CA",
        "cpv_code": "90522000",
        "source_url": "https://www.ontario.ca/page/procurement",
    },
    {
        "source": "Reference",
        "tender_id": "ref-ca-indigenous-001",
        "title": "Indigenous Community Water Treatment Systems",
        "description": "Design, construction, and commissioning of modular water treatment systems for five Indigenous communities including membrane filtration, UV disinfection, SCADA monitoring, and operator training. This procurement is set aside under the Procurement Strategy for Aboriginal Business (PSAB). The Contractor shall engage local Indigenous labour and provide capacity building and knowledge transfer to community operators.",
        "buyer": "Indigenous Services Canada",
        "value": 12000000,
        "currency": "CAD",
        "country": "CA",
        "cpv_code": "45232150",
        "source_url": "https://buyandsell.gc.ca",
    },
    {
        "source": "Reference",
        "tender_id": "ref-uk-it-001",
        "title": "Government Digital Service Platform Modernisation",
        "description": "Modernisation of the central government digital service platform including microservices architecture redesign, API gateway implementation, identity and access management, and migration to UK Government Cloud (G-Cloud). The Contractor shall comply with the Government Digital Service Standard, NCSC Cyber Essentials Plus, and UK GDPR requirements. Agile delivery methodology with two-week sprints required.",
        "buyer": "Cabinet Office — Government Digital Service",
        "value": 8000000,
        "currency": "GBP",
        "country": "GB",
        "cpv_code": "72000000",
        "source_url": "https://www.contractsfinder.service.gov.uk",
    },
    {
        "source": "Reference",
        "tender_id": "ref-uk-health-001",
        "title": "NHS Diagnostic Imaging Equipment Procurement",
        "description": "Supply, installation, and maintenance of diagnostic imaging equipment including 3T MRI scanners, CT scanners, and digital X-ray systems across 8 NHS Trust hospital sites. Equipment shall meet MHRA regulatory requirements, IEC 60601 safety standards, and DICOM interoperability standards. The contract includes 7-year full-service maintenance, training for 120+ radiographers, and guaranteed uptime of 98%.",
        "buyer": "NHS England — Procurement Division",
        "value": 25000000,
        "currency": "GBP",
        "country": "GB",
        "cpv_code": "33111000",
        "source_url": "https://www.contractsfinder.service.gov.uk",
    },
    {
        "source": "Reference",
        "tender_id": "ref-au-it-001",
        "title": "Whole-of-Government Identity and Access Management",
        "description": "Implementation of a federated identity and access management solution supporting 200,000+ government users across 50 agencies. The solution shall support multi-factor authentication, single sign-on, role-based access control, and integration with the Australian Government Digital Identity System (myGovID). All data must be stored within Australia. The Contractor shall achieve IRAP assessment at PROTECTED level.",
        "buyer": "Digital Transformation Agency — Australia",
        "value": 18000000,
        "currency": "AUD",
        "country": "AU",
        "cpv_code": "72212730",
        "source_url": "https://www.tenders.gov.au",
    },
    {
        "source": "Reference",
        "tender_id": "ref-eu-transport-001",
        "title": "Trans-European Transport Network Rail Signalling Upgrade",
        "description": "Design, supply, installation, testing, and commissioning of the European Rail Traffic Management System (ERTMS) Level 2 signalling across a 250km rail corridor. The system shall comply with EU Technical Specifications for Interoperability (TSI) and EN 50126/50128/50129 safety standards. The Contractor shall provide system integration, driver training, and 15-year in-service support with 99.5% availability guarantee.",
        "buyer": "European Commission — DG MOVE (CINEA)",
        "value": 120000000,
        "currency": "EUR",
        "country": "EU",
        "cpv_code": "34632000",
        "source_url": "https://ted.europa.eu",
    },
    {
        "source": "Reference",
        "tender_id": "ref-eu-env-001",
        "title": "Offshore Wind Farm Environmental Impact Assessment",
        "description": "Comprehensive Environmental Impact Assessment (EIA) for a proposed 500MW offshore wind farm including marine ecology surveys, ornithological studies, noise and vibration modelling, seabed characterisation, and cumulative impact assessment. The study shall comply with EU EIA Directive 2011/92/EU as amended by 2014/52/EU and the Marine Strategy Framework Directive 2008/56/EC.",
        "buyer": "European Climate Infrastructure and Environment Executive Agency",
        "value": 3500000,
        "currency": "EUR",
        "country": "EU",
        "cpv_code": "71313000",
        "source_url": "https://ted.europa.eu",
    },
    {
        "source": "Reference",
        "tender_id": "ref-ca-ai-001",
        "title": "AI-Powered Document Processing and Classification System",
        "description": "Development and deployment of an AI-powered system for automated document classification, data extraction, and workflow routing. The system shall process 500,000+ documents annually with 95% accuracy, support both official languages, and comply with the Directive on Automated Decision-Making and the Algorithmic Impact Assessment requirements. The Contractor shall provide explainability features and bias testing reports.",
        "buyer": "Immigration, Refugees and Citizenship Canada",
        "value": 5200000,
        "currency": "CAD",
        "country": "CA",
        "cpv_code": "72212517",
        "source_url": "https://buyandsell.gc.ca",
    },
    {
        "source": "Reference",
        "tender_id": "ref-ca-green-001",
        "title": "Solar Panel Installation — Federal Buildings Portfolio",
        "description": "Design, procurement, installation, and commissioning of rooftop and ground-mount solar photovoltaic systems across 25 federal buildings totalling 5MW capacity. The Contractor shall conduct structural assessments, obtain all permits, install grid-tied inverter systems with battery storage, and provide 25-year performance warranties. All systems shall comply with CSA C22.1 and the National Building Code of Canada.",
        "buyer": "Public Services and Procurement Canada",
        "value": 18500000,
        "currency": "CAD",
        "country": "CA",
        "cpv_code": "09331200",
        "source_url": "https://buyandsell.gc.ca",
    },
    {
        "source": "Reference",
        "tender_id": "ref-ca-bc-001",
        "title": "BC Wildfire Detection and Response Technology Platform",
        "description": "Development of an integrated wildfire detection and response platform combining satellite imagery, IoT sensor networks, drone surveillance, and predictive analytics. The system shall provide early warning within 15 minutes of ignition, automated resource dispatch recommendations, and real-time situational awareness dashboards for incident commanders. Integration with existing BC Wildfire Service systems required.",
        "buyer": "BC Ministry of Forests",
        "value": 9800000,
        "currency": "CAD",
        "country": "CA",
        "cpv_code": "72212000",
        "source_url": "https://www2.gov.bc.ca/gov/content/bc-bid",
    },
    {
        "source": "Reference",
        "tender_id": "ref-ca-ab-001",
        "title": "Alberta Pipeline Integrity Management System",
        "description": "Implementation of a digital pipeline integrity management system for monitoring 5,000km of energy pipeline infrastructure. The system shall include inline inspection data management, corrosion growth modelling, risk-based inspection scheduling, and regulatory reporting automation. Compliance with CSA Z662, Alberta Pipeline Act, and AER Directive 077 is mandatory.",
        "buyer": "Alberta Energy Regulator",
        "value": 7500000,
        "currency": "CAD",
        "country": "CA",
        "cpv_code": "72212000",
        "source_url": "https://vendor.purchasingconnection.ca",
    },
    {
        "source": "Reference",
        "tender_id": "ref-ca-qc-001",
        "title": "Quebec Bilingual E-Government Services Portal",
        "description": "Design, development, and deployment of a bilingual (French and English) e-government services portal providing online access to 200+ citizen services including permit applications, tax filings, health card renewal, and complaint management. The portal shall meet WCAG 2.1 AA accessibility standards, support Quebec digital identity (Service Quebecois), and achieve 99.9% availability.",
        "buyer": "Government of Quebec — Centre de services partagés du Québec",
        "value": 14000000,
        "currency": "CAD",
        "country": "CA",
        "cpv_code": "72413000",
        "source_url": "https://www.seao.ca",
    },
    {
        "source": "Reference",
        "tender_id": "ref-ca-edu-001",
        "title": "Learning Management System for Federal Training Programs",
        "description": "Procurement of a cloud-based Learning Management System (LMS) supporting 300,000+ federal employees with SCORM/xAPI compliance, bilingual interface, mobile accessibility, virtual classroom integration, and automated competency tracking. The system shall integrate with the Canada School of Public Service curriculum and support GCKey authentication. Data residency in Canada required.",
        "buyer": "Canada School of Public Service",
        "value": 4200000,
        "currency": "CAD",
        "country": "CA",
        "cpv_code": "48190000",
        "source_url": "https://buyandsell.gc.ca",
    },
    {
        "source": "Reference",
        "tender_id": "ref-eu-digital-001",
        "title": "Digital Single Market — Cross-Border E-Invoicing Platform",
        "description": "Development of a pan-European cross-border e-invoicing platform supporting the European Standard EN 16931 and the eDelivery building block (AS4/SMP). The platform shall process 10 million invoices annually across 27 member states, support PEPPOL network integration, and provide real-time VAT validation. Compliance with eIDAS Regulation for electronic signatures and seals required.",
        "buyer": "European Commission — DG DIGIT",
        "value": 6000000,
        "currency": "EUR",
        "country": "EU",
        "cpv_code": "72212463",
        "source_url": "https://ted.europa.eu",
    },
    {
        "source": "Reference",
        "tender_id": "ref-ca-telecom-001",
        "title": "Rural Broadband Connectivity — Northern Ontario",
        "description": "Design, build, and operate a fibre-to-the-premises (FTTP) broadband network delivering minimum 50/10 Mbps service to 15,000 households in underserved communities in Northern Ontario. The project is funded under the Universal Broadband Fund and shall comply with CRTC basic service objectives. The Contractor shall provide open-access wholesale services and submit quarterly progress reports to ISED.",
        "buyer": "Innovation, Science and Economic Development Canada",
        "value": 32000000,
        "currency": "CAD",
        "country": "CA",
        "cpv_code": "32412100",
        "source_url": "https://buyandsell.gc.ca",
    },
    {
        "source": "Reference",
        "tender_id": "ref-au-con-001",
        "title": "Sydney Metro West Station Construction — Stage 2",
        "description": "Construction of two underground metro stations including excavation, structural works, architectural fitout, mechanical and electrical services, and platform screen doors. The Contractor shall comply with Australian Standards AS 4292 (Railway Safety Management) and NSW Work Health and Safety Regulation 2017. Design life of 100 years for structural elements required.",
        "buyer": "Sydney Metro — NSW Government",
        "value": 850000000,
        "currency": "AUD",
        "country": "AU",
        "cpv_code": "45234100",
        "source_url": "https://www.tenders.gov.au",
    },
    {
        "source": "Reference",
        "tender_id": "ref-ca-fin-001",
        "title": "Anti-Money Laundering Transaction Monitoring System",
        "description": "Implementation of an AI-driven anti-money laundering (AML) transaction monitoring and suspicious transaction reporting system. The system shall process 5 million daily transactions, support rule-based and machine-learning detection models, generate STR/CTR reports compliant with FINTRAC requirements, and integrate with existing core banking systems via API. The Contractor shall provide model validation and annual tuning.",
        "buyer": "Financial Transactions and Reports Analysis Centre of Canada",
        "value": 8700000,
        "currency": "CAD",
        "country": "CA",
        "cpv_code": "72212463",
        "source_url": "https://buyandsell.gc.ca",
    },
    {
        "source": "Reference",
        "tender_id": "ref-ca-space-001",
        "title": "Earth Observation Satellite Data Processing Infrastructure",
        "description": "Development of a scalable cloud-native data processing and analytics platform for earth observation satellite imagery supporting the RADARSAT Constellation Mission. The platform shall ingest, process, archive, and distribute 2TB of satellite data daily with automated orthorectification, change detection, and AI-based feature extraction. Protected B data handling capabilities required.",
        "buyer": "Canadian Space Agency",
        "value": 11000000,
        "currency": "CAD",
        "country": "CA",
        "cpv_code": "72314000",
        "source_url": "https://buyandsell.gc.ca",
    },
    {
        "source": "Reference",
        "tender_id": "ref-ca-justice-001",
        "title": "Court Case Management System Modernization",
        "description": "Modernization of the federal court case management system supporting 4,000+ users across the Federal Court, Federal Court of Appeal, Tax Court, and Court Martial Appeal Court. The system shall support e-filing, digital courtroom workflows, automated scheduling, and bilingual document management. Integration with the Justice sector ICON network and compliance with the Federal Courts Rules required.",
        "buyer": "Courts Administration Service",
        "value": 6800000,
        "currency": "CAD",
        "country": "CA",
        "cpv_code": "48219000",
        "source_url": "https://buyandsell.gc.ca",
    },
    {
        "source": "Reference",
        "tender_id": "ref-uk-defence-001",
        "title": "Armoured Vehicle Fleet Maintenance and Logistics Support",
        "description": "Provision of through-life maintenance, repair, and overhaul services for a fleet of 400+ armoured vehicles including scheduled and unscheduled maintenance, spare parts supply chain management, technical documentation updates, and field service support. The Contractor shall maintain 85% operational availability and comply with DEF STAN 00-600 and NATO STANAG logistics standards.",
        "buyer": "UK Ministry of Defence — Defence Equipment and Support",
        "value": 180000000,
        "currency": "GBP",
        "country": "GB",
        "cpv_code": "50600000",
        "source_url": "https://www.contractsfinder.service.gov.uk",
    },
    {
        "source": "Reference",
        "tender_id": "ref-ca-accessibility-001",
        "title": "Accessible Digital Content Remediation Services",
        "description": "Remediation of 10,000+ digital documents (PDF, Word, Excel, PowerPoint) and 500+ web pages to meet WCAG 2.1 Level AA and PDF/UA standards. The Contractor shall provide automated scanning, manual accessibility testing with assistive technologies (JAWS, NVDA, VoiceOver), alternative text for images, proper heading structures, and accessible table markup. Compliance with the Accessible Canada Act, SC 2019, c 10 required.",
        "buyer": "Accessibility Standards Canada",
        "value": 1200000,
        "currency": "CAD",
        "country": "CA",
        "cpv_code": "72413000",
        "source_url": "https://buyandsell.gc.ca",
    },
]


def seed_tenders(db: Session) -> int:
    """
    Insert reference tenders if none exist. Returns count inserted.
    Provides fallback content when TED/OCP APIs are unavailable.
    """
    existing = db.query(Tender).filter(Tender.source == "Reference").count()
    if existing >= len(SEED_TENDERS):
        return 0

    existing_ids = set()
    if existing > 0:
        for row in db.query(Tender.tender_id).filter(Tender.source == "Reference").all():
            existing_ids.add(row[0])

    inserted = 0
    for data in SEED_TENDERS:
        if data["tender_id"] in existing_ids:
            continue
        tender = Tender(**data)
        db.add(tender)
        inserted += 1

    db.commit()
    return inserted
