"""Commercial / Corporate clauses — M&A, shareholder, guarantee, promissory notes."""

COMMERCIAL_CLAUSES = [
    # ── Share Purchase / M&A ─────────────────────────────────
    {
        "source": "O'Brien_Forms",
        "clause_type": "Representations_Warranties",
        "subtype": "Vendor_Representations_SPA",
        "clause_text": "The Vendor represents and warrants to the Purchaser that: (a) the Vendor is the registered and beneficial owner of the Shares free and clear of all liens, encumbrances, and third-party interests; (b) the Corporation is duly incorporated and in good standing under the laws of Ontario; (c) the financial statements fairly present the financial position of the Corporation as at the date thereof in accordance with GAAP; and (d) there are no pending or threatened actions, suits, or proceedings against the Corporation.",
        "jurisdiction": "CA-ON",
        "industry": "General",
        "risk_level": "Medium",
        "is_standard": True,
    },
    {
        "source": "O'Brien_Forms",
        "clause_type": "Representations_Warranties",
        "subtype": "Purchaser_Representations_SPA",
        "clause_text": "The Purchaser represents and warrants to the Vendor that: (a) the Purchaser has the corporate power and authority to enter into this Agreement and to complete the transactions contemplated hereby; (b) this Agreement has been duly authorized, executed, and delivered by the Purchaser and constitutes a legal, valid, and binding obligation; and (c) the Purchaser has sufficient funds available to pay the Purchase Price at Closing.",
        "jurisdiction": "CA-ON",
        "industry": "General",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "ContractCodex",
        "clause_type": "Indemnification",
        "subtype": "Vendor_Indemnity_SPA",
        "clause_text": "The Vendor shall indemnify and hold harmless the Purchaser from and against all losses, damages, claims, costs, and expenses arising from any breach of the Vendor's representations, warranties, or covenants in this Agreement. The Vendor's aggregate liability shall not exceed the Purchase Price. Claims must be notified within eighteen (18) months of the Closing Date, except for claims relating to tax or title to the Shares, which survive indefinitely.",
        "jurisdiction": "CA-ON",
        "industry": "General",
        "risk_level": "Medium",
        "is_standard": True,
    },
    {
        "source": "ContractCodex",
        "clause_type": "Closing_Conditions",
        "subtype": "Conditions_Precedent",
        "clause_text": "The obligation of the Purchaser to complete the purchase of the Shares is subject to the satisfaction or waiver of the following conditions: (a) all representations and warranties of the Vendor are true and correct at Closing; (b) the Vendor has performed all covenants required prior to Closing; (c) all required regulatory approvals have been obtained including under the Competition Act, RSC 1985, c C-34; and (d) no material adverse change has occurred since the date of this Agreement.",
        "jurisdiction": "CA-ON",
        "industry": "General",
        "risk_level": "Medium",
        "is_standard": True,
    },
    {
        "source": "ContractCodex",
        "clause_type": "Material_Adverse_Change",
        "subtype": "MAC_Clause",
        "clause_text": "Material Adverse Change means any change, event, or occurrence that, individually or in the aggregate, has or would reasonably be expected to have a material adverse effect on the business, assets, liabilities, financial condition, or results of operations of the Corporation, but excludes changes arising from: (a) general economic or market conditions; (b) changes in applicable law; (c) changes affecting the industry generally; or (d) the announcement of this Agreement.",
        "jurisdiction": "CA-ON",
        "industry": "General",
        "risk_level": "High",
        "is_standard": True,
    },
    # ── Shareholder Agreement ────────────────────────────────
    {
        "source": "O'Brien_Forms",
        "clause_type": "Shareholder_Rights",
        "subtype": "Drag_Along",
        "clause_text": "If shareholders holding not less than sixty-six and two-thirds percent (66.67%) of the issued and outstanding shares (the 'Majority Shareholders') accept a bona fide offer from a third party to purchase all of the shares, the Majority Shareholders shall have the right to require the remaining shareholders to sell their shares on the same terms and conditions. The remaining shareholders shall execute all documents necessary to complete such sale within fifteen (15) business days.",
        "jurisdiction": "CA-ON",
        "industry": "General",
        "risk_level": "Medium",
        "is_standard": True,
    },
    {
        "source": "O'Brien_Forms",
        "clause_type": "Shareholder_Rights",
        "subtype": "Tag_Along",
        "clause_text": "If any shareholder (the 'Selling Shareholder') proposes to sell or transfer shares to a third party, each other shareholder shall have the right (but not the obligation) to participate in such sale on a pro rata basis and on the same terms and conditions offered to the Selling Shareholder. The Selling Shareholder shall provide not less than thirty (30) days' written notice of the proposed sale.",
        "jurisdiction": "CA-ON",
        "industry": "General",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "O'Brien_Forms",
        "clause_type": "Shareholder_Rights",
        "subtype": "Shotgun_Buy_Sell",
        "clause_text": "Any shareholder (the 'Offeror') may at any time deliver a notice to the other shareholders (the 'Offerees') offering to purchase all of the Offerees' shares at a price per share specified in the notice. Within thirty (30) days of receipt, each Offeree must either: (a) accept the offer and sell; or (b) purchase all of the Offeror's shares at the same price per share. Failure to respond within the thirty-day period shall be deemed acceptance of the offer.",
        "jurisdiction": "CA-ON",
        "industry": "General",
        "risk_level": "High",
        "is_standard": True,
    },
    {
        "source": "O'Brien_Forms",
        "clause_type": "Shareholder_Rights",
        "subtype": "Right_First_Refusal",
        "clause_text": "Before any shareholder may sell, transfer, or otherwise dispose of any shares, the shareholder shall first offer such shares to the other shareholders on the same terms and conditions as the proposed transfer. The other shareholders shall have thirty (30) days to accept the offer in whole or in part, pro rata to their existing shareholdings. If the offer is not accepted, the selling shareholder may complete the transfer to the third party within sixty (60) days on terms no more favourable.",
        "jurisdiction": "CA-ON",
        "industry": "General",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "O'Brien_Forms",
        "clause_type": "Shareholder_Rights",
        "subtype": "Unanimous_Shareholder_Agreement",
        "clause_text": "Pursuant to section 146 of the Business Corporations Act, RSO 1990, c B.16, the shareholders unanimously agree to restrict the powers of the directors to manage or supervise the management of the business and affairs of the Corporation. The following matters shall require the unanimous written consent of all shareholders: (a) any amendment to the articles; (b) the issuance of additional shares; (c) any sale of substantially all assets; (d) any borrowing in excess of $100,000; and (e) the declaration of dividends.",
        "jurisdiction": "CA-ON",
        "industry": "General",
        "risk_level": "Medium",
        "is_standard": True,
    },
    # ── Guarantee / Promissory Note ──────────────────────────
    {
        "source": "O'Brien_Forms",
        "clause_type": "Guarantee",
        "subtype": "Personal_Guarantee",
        "clause_text": "The Guarantor unconditionally and irrevocably guarantees to the Creditor the due and punctual payment and performance of all present and future obligations of the Debtor under the Agreement. This guarantee is a continuing guarantee and shall remain in full force until all obligations are satisfied. The Guarantor waives all rights of subrogation until the Creditor has been paid in full. The Creditor may proceed directly against the Guarantor without first pursuing remedies against the Debtor.",
        "jurisdiction": "CA-ON",
        "industry": "General",
        "risk_level": "High",
        "is_standard": True,
    },
    {
        "source": "O'Brien_Forms",
        "clause_type": "Promissory_Note",
        "subtype": "Demand_Note",
        "clause_text": "FOR VALUE RECEIVED, the undersigned (the 'Maker') promises to pay to the order of the Payee the principal sum of [AMOUNT] Canadian dollars, together with interest thereon at the rate of [X]% per annum, calculated and compounded monthly, payable on demand. Upon default in payment, interest shall accrue at the rate of [X+2]% per annum. The Maker waives presentment, demand, protest, and notice of dishonour. This Note shall be governed by the laws of Ontario and the Bills of Exchange Act, RSC 1985, c B-4.",
        "jurisdiction": "CA-ON",
        "industry": "General",
        "risk_level": "Medium",
        "is_standard": True,
    },
    {
        "source": "ContractCodex",
        "clause_type": "Non_Competition",
        "subtype": "Business_Sale_Non_Compete",
        "clause_text": "For a period of two (2) years following the Closing Date, the Vendor shall not, directly or indirectly, within a radius of 100 kilometres of any location where the Business is carried on, engage in, carry on, or be employed by any business that competes with the Business. The parties acknowledge that this restriction is reasonable and necessary to protect the goodwill purchased by the Purchaser and the consideration paid therefor.",
        "jurisdiction": "CA-ON",
        "industry": "General",
        "risk_level": "Medium",
        "is_standard": True,
    },
    {
        "source": "ContractCodex",
        "clause_type": "Non_Solicitation",
        "subtype": "Customer_Employee_Non_Solicit",
        "clause_text": "For a period of two (2) years following the Closing Date, the Vendor shall not, directly or indirectly: (a) solicit, canvass, or accept business from any customer or client of the Business; or (b) recruit, hire, solicit, or induce any employee, contractor, or consultant of the Business to leave their engagement. This restriction applies to customers and employees with whom the Vendor had material contact during the twelve (12) months prior to Closing.",
        "jurisdiction": "CA-ON",
        "industry": "General",
        "risk_level": "Medium",
        "is_standard": True,
    },
]
