"""Compliance & Regulatory clauses — privacy, accessibility, anti-corruption, labour."""

COMPLIANCE_CLAUSES = [
    {
        "source": "Ontario",
        "clause_type": "Compliance_Regulatory",
        "subtype": "PIPEDA_Privacy",
        "clause_text": "The Contractor shall comply with the Personal Information Protection and Electronic Documents Act, SC 2000, c 5, and the Freedom of Information and Protection of Privacy Act, RSO 1990, c F-31, in its collection, use, and disclosure of personal information under this Contract.",
        "jurisdiction": "CA-ON",
        "industry": "General",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "Ontario",
        "clause_type": "Compliance_Regulatory",
        "subtype": "FIPPA_Ontario",
        "clause_text": "The Contractor acknowledges that records created or received in the performance of this Contract may be subject to the Freedom of Information and Protection of Privacy Act, RSO 1990, c F-31 (FIPPA). The Contractor shall assist Ontario in responding to access requests and shall not destroy any records that may be subject to FIPPA without the prior written approval of Ontario.",
        "jurisdiction": "CA-ON",
        "industry": "General",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "Ontario",
        "clause_type": "Compliance_Regulatory",
        "subtype": "AODA_Accessibility",
        "clause_text": "All deliverables, systems, and digital content provided under this Contract must comply with the Accessibility for Ontarians with Disabilities Act, 2005, SO 2005, c 11 (AODA), including the Integrated Accessibility Standards Regulation, O Reg 191/11, and meet or exceed WCAG 2.1 Level AA conformance for all web-based content and applications.",
        "jurisdiction": "CA-ON",
        "industry": "IT",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "Federal",
        "clause_type": "Compliance_Regulatory",
        "subtype": "Official_Languages",
        "clause_text": "All deliverables, reports, user interfaces, and public-facing materials shall be provided in both official languages (English and French) in accordance with the Official Languages Act, RSC 1985, c 31 (4th Supp). Translation shall be of professional quality and subject to review by Canada's official languages coordinator.",
        "jurisdiction": "CA-Federal",
        "industry": "General",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "Federal",
        "clause_type": "Compliance_Regulatory",
        "subtype": "Anti_Corruption_CFPOA",
        "clause_text": "The Contractor represents and warrants that neither the Contractor nor any of its agents, employees, or subcontractors has, directly or indirectly, paid, offered, or promised any bribe, gift, or other improper advantage to any public official in connection with this Contract, in violation of the Corruption of Foreign Public Officials Act, SC 1998, c 34 (CFPOA) or the Criminal Code, RSC 1985, c C-46.",
        "jurisdiction": "CA-Federal",
        "industry": "General",
        "risk_level": "High",
        "is_standard": True,
    },
    {
        "source": "Federal",
        "clause_type": "Compliance_Regulatory",
        "subtype": "Trade_Compliance",
        "clause_text": "The Contractor shall comply with all applicable Canadian export control laws including the Export and Import Permits Act, RSC 1985, c E-19, the Defence Production Act, RSC 1985, c D-1, and the Special Economic Measures Act, SC 1992, c 17. The Contractor shall not export or re-export any controlled goods, technology, or technical data without the required permits.",
        "jurisdiction": "CA-Federal",
        "industry": "General",
        "risk_level": "High",
        "is_standard": True,
    },
    {
        "source": "Ontario",
        "clause_type": "Compliance_Regulatory",
        "subtype": "Labour_Standards",
        "clause_text": "The Contractor shall comply with all applicable federal and provincial employment and labour standards legislation, including the Canada Labour Code, RSC 1985, c L-2, the Employment Standards Act, 2000, SO 2000, c 41, and all applicable collective bargaining agreements. The Contractor shall pay all workers at or above minimum wage and shall not engage in any form of forced or child labour.",
        "jurisdiction": "CA-ON",
        "industry": "General",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "Ontario",
        "clause_type": "Compliance_Regulatory",
        "subtype": "Health_Safety",
        "clause_text": "The Contractor shall comply with the Occupational Health and Safety Act, RSO 1990, c O.1, and all applicable workplace health and safety regulations. The Contractor shall maintain a health and safety program, provide all necessary personal protective equipment, and report all workplace incidents to the appropriate authorities and to the Technical Authority within twenty-four (24) hours.",
        "jurisdiction": "CA-ON",
        "industry": "Construction",
        "risk_level": "Medium",
        "is_standard": True,
    },
    {
        "source": "Federal",
        "clause_type": "Compliance_Regulatory",
        "subtype": "Environmental_Compliance",
        "clause_text": "The Contractor shall comply with all applicable federal and provincial environmental legislation, including the Canadian Environmental Protection Act, 1999, SC 1999, c 33, the Impact Assessment Act, SC 2019, c 28, and the Transportation of Dangerous Goods Act, 1992, SC 1992, c 34. The Contractor shall be responsible for the proper handling, storage, and disposal of all hazardous materials.",
        "jurisdiction": "CA-Federal",
        "industry": "Construction",
        "risk_level": "Medium",
        "is_standard": True,
    },
    {
        "source": "Federal",
        "clause_type": "Compliance_Regulatory",
        "subtype": "Pay_Equity",
        "clause_text": "The Contractor shall comply with the Pay Equity Act, SC 2018, c 27, s 416, and shall ensure equal pay for work of equal value within its organization. For contracts valued at $1,000,000 or more, the Contractor shall provide certification of compliance with the Federal Contractors Program for Employment Equity, as required by the Employment Equity Act, SC 1995, c 44.",
        "jurisdiction": "CA-Federal",
        "industry": "General",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "Federal",
        "clause_type": "Compliance_Regulatory",
        "subtype": "Modern_Slavery",
        "clause_text": "The Contractor represents that it has implemented measures to identify and mitigate the risk of forced labour and child labour in its supply chains, in accordance with the Fighting Against Forced Labour and Child Labour in Supply Chains Act, SC 2023, c 9. The Contractor shall, upon request, provide Canada with its most recent report filed under the Act.",
        "jurisdiction": "CA-Federal",
        "industry": "General",
        "risk_level": "Medium",
        "is_standard": True,
    },
    {
        "source": "Federal",
        "clause_type": "Compliance_Regulatory",
        "subtype": "Sanctions_Compliance",
        "clause_text": "The Contractor certifies that neither the Contractor nor any of its directors, officers, or beneficial owners is a designated person under the Special Economic Measures Act, SC 1992, c 17, the Justice for Victims of Corrupt Foreign Officials Act, SC 2017, c 21, or the United Nations Act, RSC 1985, c U-2. The Contractor shall not engage any sanctioned entity in the performance of this Contract.",
        "jurisdiction": "CA-Federal",
        "industry": "General",
        "risk_level": "High",
        "is_standard": True,
    },
]
