"""Core contract terms — Entire Agreement, Governing Law, Force Majeure, etc."""

CORE_CLAUSES = [
    {
        "source": "SACC",
        "clause_type": "Entire_Agreement",
        "subtype": "Integration",
        "clause_text": "This Contract, including all schedules and amendments, constitutes the entire agreement between the parties with respect to its subject matter and supersedes all prior negotiations, representations, warranties, understandings, and agreements, whether written or oral.",
        "jurisdiction": "CA-Federal",
        "industry": "General",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "Ontario",
        "clause_type": "Governing_Law",
        "subtype": "Ontario_Jurisdiction",
        "clause_text": "This Contract shall be governed by and construed in accordance with the laws of the Province of Ontario and the federal laws of Canada applicable therein. Each party irrevocably attorns to the exclusive jurisdiction of the courts of Ontario.",
        "jurisdiction": "CA-ON",
        "industry": "General",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "BC",
        "clause_type": "Governing_Law",
        "subtype": "BC_Jurisdiction",
        "clause_text": "This Contract shall be governed by the laws of the Province of British Columbia and the federal laws of Canada applicable therein. The parties irrevocably submit to the exclusive jurisdiction of the courts of British Columbia sitting in Vancouver.",
        "jurisdiction": "CA-BC",
        "industry": "General",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "Federal",
        "clause_type": "Governing_Law",
        "subtype": "Federal_Jurisdiction",
        "clause_text": "This Contract shall be interpreted and governed in accordance with the laws in force in the province or territory where the Work is performed, or if performed in more than one jurisdiction, the laws of Ontario, and the federal laws of Canada applicable therein.",
        "jurisdiction": "CA-Federal",
        "industry": "General",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "SACC",
        "clause_type": "Amendments",
        "subtype": "Written_Amendments",
        "clause_text": "No amendment, modification, or supplement to this Contract shall be valid or binding unless set out in a formal written amendment executed by the duly authorized representatives of both parties. No waiver of any provision shall constitute a waiver of any other provision.",
        "jurisdiction": "CA-Federal",
        "industry": "General",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "SACC",
        "clause_type": "Severability",
        "subtype": "Partial_Invalidity",
        "clause_text": "If any provision of this Contract is determined to be invalid or unenforceable by a court of competent jurisdiction, such determination shall not affect the validity or enforceability of the remaining provisions, which shall continue in full force and effect.",
        "jurisdiction": "CA-Federal",
        "industry": "General",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "SACC",
        "clause_type": "Waiver",
        "subtype": "No_Implied_Waiver",
        "clause_text": "The failure of either party to insist upon strict performance of any term or condition of this Contract, or to exercise any right or remedy consequent upon breach, shall not constitute a waiver of any such term, condition, right, or remedy for that or any subsequent breach.",
        "jurisdiction": "CA-Federal",
        "industry": "General",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "SACC",
        "clause_type": "Assignment",
        "subtype": "No_Assignment_Without_Consent",
        "clause_text": "The Contractor shall not assign this Contract or any part thereof, or any benefit or interest therein, without the prior written consent of Canada. Any assignment made without such consent shall be void and of no effect. Canada may assign its rights under this Contract to any federal department or agency.",
        "jurisdiction": "CA-Federal",
        "industry": "General",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "SACC",
        "clause_type": "Notices",
        "subtype": "Written_Notices",
        "clause_text": "Any notice, demand, or other communication required or permitted under this Contract shall be in writing and shall be deemed to have been duly given when delivered personally, sent by registered mail, or transmitted by email with confirmed receipt to the addresses set out in the Contract.",
        "jurisdiction": "CA-Federal",
        "industry": "General",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "SACC",
        "clause_type": "Force_Majeure",
        "subtype": "Standard",
        "clause_text": "Neither party shall be liable for any delay or failure to perform its obligations under this Contract if such delay or failure results from a Force Majeure Event, including but not limited to acts of God, war, terrorism, fire, flood, earthquake, epidemic, pandemic, governmental action, labour disputes, or any other cause beyond the reasonable control of the affected party. The affected party shall promptly notify the other party and use commercially reasonable efforts to resume performance.",
        "jurisdiction": "CA-Federal",
        "industry": "General",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "Ontario",
        "clause_type": "Force_Majeure",
        "subtype": "Pandemic_Extended",
        "clause_text": "In addition to the standard Force Majeure events, the parties acknowledge that pandemic, epidemic, or public health emergency declared by federal, provincial, or municipal authorities, including quarantine orders and mandatory lockdowns, shall constitute Force Majeure. The affected party shall provide notice within five (5) business days and the parties shall negotiate in good faith to adjust schedules and deliverables.",
        "jurisdiction": "CA-ON",
        "industry": "General",
        "risk_level": "Medium",
        "is_standard": True,
    },
    {
        "source": "SACC",
        "clause_type": "Survival",
        "subtype": "Post_Termination",
        "clause_text": "The provisions of this Contract relating to confidentiality, intellectual property, indemnification, limitation of liability, audit rights, and any other provision which by its nature is intended to survive, shall survive the expiration or termination of this Contract.",
        "jurisdiction": "CA-Federal",
        "industry": "General",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "SACC",
        "clause_type": "Order_of_Precedence",
        "subtype": "Document_Hierarchy",
        "clause_text": "In the event of any conflict or inconsistency between the documents forming this Contract, the following order of precedence shall apply: (a) the Articles of Agreement; (b) Supplemental General Conditions; (c) General Conditions; (d) the Statement of Work; (e) Annexes and Schedules. The document higher in precedence shall prevail to the extent of the conflict.",
        "jurisdiction": "CA-Federal",
        "industry": "General",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "SACC",
        "clause_type": "Independent_Contractor",
        "subtype": "No_Employment",
        "clause_text": "The Contractor is an independent contractor and nothing in this Contract shall be construed as creating an employment, partnership, joint venture, or agency relationship between the Contractor and Canada. The Contractor shall be solely responsible for all statutory deductions, employment insurance premiums, and Canada Pension Plan contributions for its personnel.",
        "jurisdiction": "CA-Federal",
        "industry": "General",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "SACC",
        "clause_type": "Representations_Warranties",
        "subtype": "Contractor_Representations",
        "clause_text": "The Contractor represents and warrants that: (a) it has the legal capacity and authority to enter into this Contract; (b) it holds all licences and permits required by law; (c) it has the experience, qualifications, and resources to perform the Work; and (d) all information provided in its bid or proposal is accurate and complete in all material respects.",
        "jurisdiction": "CA-Federal",
        "industry": "General",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "Ontario",
        "clause_type": "Set_Off",
        "subtype": "Crown_Set_Off",
        "clause_text": "Canada may set off against any amount payable to the Contractor under this Contract any amount payable by the Contractor to Canada under this Contract or under any other contract or obligation. The Contractor shall be given reasonable notice before any set-off is applied.",
        "jurisdiction": "CA-ON",
        "industry": "General",
        "risk_level": "Medium",
        "is_standard": True,
    },
]
