"""Employment law clauses — termination, non-compete, IP assignment, policies."""

EMPLOYMENT_CLAUSES = [
    {
        "source": "Fynk",
        "clause_type": "Employment",
        "subtype": "Termination_Without_Cause",
        "clause_text": "The Employer may terminate this Agreement without cause by providing written notice or pay in lieu of notice in accordance with the Employment Standards Act, 2000, SO 2000, c 41, and the common law. The Employee shall be entitled to the greater of: (a) the minimum notice or termination pay required under the ESA; or (b) reasonable notice at common law, having regard to the Employee's age, length of service, character of employment, and availability of similar employment.",
        "jurisdiction": "CA-ON",
        "industry": "General",
        "risk_level": "Medium",
        "is_standard": True,
    },
    {
        "source": "Fynk",
        "clause_type": "Employment",
        "subtype": "Termination_With_Cause",
        "clause_text": "The Employer may terminate this Agreement immediately for just cause without notice or pay in lieu thereof. Just cause includes but is not limited to: (a) dishonesty, fraud, or theft; (b) wilful misconduct or insubordination; (c) material breach of this Agreement or Company policies; (d) conviction of a criminal offence relevant to the Employee's duties; or (e) conduct that brings the Employer into disrepute. The Employer shall provide the Employee with written particulars of the cause relied upon.",
        "jurisdiction": "CA-ON",
        "industry": "General",
        "risk_level": "Medium",
        "is_standard": True,
    },
    {
        "source": "Fynk",
        "clause_type": "Employment",
        "subtype": "Termination_Clause_ESA",
        "clause_text": "Notwithstanding any other provision of this Agreement, in no event shall the Employee receive less than the minimum entitlements to notice of termination, termination pay, and severance pay (if applicable) required under the Employment Standards Act, 2000, SO 2000, c 41, as amended. Any provision of this Agreement that provides less than the ESA minimum shall be deemed to be amended to provide the ESA minimum.",
        "jurisdiction": "CA-ON",
        "industry": "General",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "O'Brien_Forms",
        "clause_type": "Employment",
        "subtype": "Non_Compete_Employee",
        "clause_text": "During the term of employment and for a period of twelve (12) months following the date of termination for any reason, the Employee shall not, directly or indirectly, within the Province of Ontario, engage in or carry on any business that is competitive with the Business of the Employer. The Employee acknowledges that this restriction is reasonable in scope, duration, and geographic extent and is necessary to protect the Employer's legitimate business interests including trade secrets and customer relationships.",
        "jurisdiction": "CA-ON",
        "industry": "General",
        "risk_level": "High",
        "is_standard": True,
    },
    {
        "source": "O'Brien_Forms",
        "clause_type": "Employment",
        "subtype": "Non_Solicitation_Employee",
        "clause_text": "For a period of twelve (12) months following termination, the Employee shall not: (a) solicit or attempt to solicit any customer, client, or prospective client of the Employer with whom the Employee had material dealings; or (b) recruit, solicit, or induce any employee or contractor of the Employer to leave the Employer's employment or engagement. The Employee acknowledges receiving adequate consideration for this covenant.",
        "jurisdiction": "CA-ON",
        "industry": "General",
        "risk_level": "Medium",
        "is_standard": True,
    },
    {
        "source": "ContractCodex",
        "clause_type": "Intellectual_Property",
        "subtype": "Employee_IP_Assignment",
        "clause_text": "All inventions, works, designs, software, trade secrets, and other intellectual property created, conceived, or developed by the Employee during the course of employment, or using the Employer's resources, information, or facilities, shall be the exclusive property of the Employer. The Employee hereby assigns to the Employer all right, title, and interest in such intellectual property and agrees to execute all documents necessary to perfect such assignment. The Employee waives all moral rights pursuant to the Copyright Act, RSC 1985, c C-42.",
        "jurisdiction": "CA-ON",
        "industry": "General",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "Fynk",
        "clause_type": "Employment",
        "subtype": "Probationary_Period",
        "clause_text": "The Employee's employment shall be subject to a probationary period of three (3) months commencing on the start date. During the probationary period, the Employer may terminate this Agreement by providing one (1) week's written notice or pay in lieu thereof. Upon successful completion of the probationary period, the Employee shall be confirmed in the position and shall be entitled to the full benefits of employment.",
        "jurisdiction": "CA-ON",
        "industry": "General",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "ContractCodex",
        "clause_type": "Employment",
        "subtype": "Severance_Release",
        "clause_text": "In consideration of the severance payment described herein, the Employee hereby releases and forever discharges the Employer, its directors, officers, employees, and agents from any and all claims, actions, causes of action, demands, and complaints arising out of or in connection with the employment or its termination, including claims under the Employment Standards Act, the Human Rights Code, RSO 1990, c H.19, and at common law. The Employee acknowledges having had the opportunity to obtain independent legal advice.",
        "jurisdiction": "CA-ON",
        "industry": "General",
        "risk_level": "Medium",
        "is_standard": True,
    },
    {
        "source": "Fynk",
        "clause_type": "Employment",
        "subtype": "Remote_Work",
        "clause_text": "The Employee may perform work remotely from a location approved by the Employer. The Employee shall maintain a dedicated workspace that meets health and safety requirements, ensure the security of Company data and equipment, and be available during core business hours. The Employer shall provide necessary equipment and reimburse reasonable expenses. Either party may revoke the remote work arrangement with thirty (30) days' notice.",
        "jurisdiction": "CA-ON",
        "industry": "General",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "O'Brien_Forms",
        "clause_type": "Employment",
        "subtype": "Policy_Incorporation",
        "clause_text": "The Employee agrees to comply with all policies, procedures, and codes of conduct of the Employer as amended from time to time, including the Workplace Harassment Policy, Privacy Policy, Acceptable Use Policy, and Code of Ethics. The Employer shall provide reasonable notice of material changes to policies. Breach of a material policy may constitute cause for termination.",
        "jurisdiction": "CA-ON",
        "industry": "General",
        "risk_level": "Low",
        "is_standard": True,
    },
]
