"""Financial terms — payment, holdback, pricing, taxes, audit."""

FINANCIAL_CLAUSES = [
    {
        "source": "SACC",
        "clause_type": "Commercial_Terms",
        "subtype": "Payment_Net_30",
        "clause_text": "Canada shall pay undisputed invoices within thirty (30) calendar days of receipt of a properly rendered invoice. Invoices must include the Contract number, a description of the work performed, the period covered, and the Contractor's GST/HST registration number. Late payments shall accrue interest at the rate prescribed under the Interest and Administrative Charges Regulations, SOR/96-188.",
        "jurisdiction": "CA-Federal",
        "industry": "General",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "SACC",
        "clause_type": "Commercial_Terms",
        "subtype": "Progress_Payments",
        "clause_text": "Progress payments shall be made monthly based on the percentage of Work completed to the satisfaction of the Technical Authority, as certified by the Project Manager. Each progress claim shall be accompanied by supporting documentation including timesheets, expense receipts, and a progress report detailing work completed in the period.",
        "jurisdiction": "CA-Federal",
        "industry": "Construction",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "SACC",
        "clause_type": "Commercial_Terms",
        "subtype": "Holdback_Retainage",
        "clause_text": "Canada shall retain a holdback of ten percent (10%) from each progress payment until Substantial Completion of the Work has been certified. The holdback shall be released forty-five (45) days after the date of Substantial Completion, provided that the Contractor has completed all deficiency work and no liens have been registered against the Work under the applicable provincial lien legislation.",
        "jurisdiction": "CA-Federal",
        "industry": "Construction",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "SACC",
        "clause_type": "Commercial_Terms",
        "subtype": "Price_Escalation_CPI",
        "clause_text": "Contract rates shall be subject to annual adjustment on each anniversary of the Contract effective date based on the Consumer Price Index (CPI) for Canada, All Items, as published by Statistics Canada (CANSIM Table 18-10-0004-01). The adjustment shall be calculated as the percentage change in CPI over the preceding twelve (12) months and shall not exceed three percent (3%) in any single year.",
        "jurisdiction": "CA-Federal",
        "industry": "General",
        "risk_level": "Medium",
        "is_standard": True,
    },
    {
        "source": "SACC",
        "clause_type": "Commercial_Terms",
        "subtype": "Fixed_Price",
        "clause_text": "The Contract Price is a firm fixed price of the amount set out in the Articles of Agreement and includes all costs, overhead, profit, and applicable taxes (except GST/HST). The Contractor shall bear all risk of cost overruns. No increase to the Contract Price shall be permitted unless authorized by a formal amendment.",
        "jurisdiction": "CA-Federal",
        "industry": "General",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "SACC",
        "clause_type": "Commercial_Terms",
        "subtype": "Time_Materials",
        "clause_text": "Payment shall be on a time-and-materials basis at the per diem or hourly rates set out in Schedule B (Basis of Payment). The Contractor shall not exceed the Contract ceiling price without prior written authorization. All expenses must be pre-approved and substantiated with original receipts. Travel expenses shall be reimbursed in accordance with the Treasury Board Travel Directive.",
        "jurisdiction": "CA-Federal",
        "industry": "Consulting",
        "risk_level": "Medium",
        "is_standard": True,
    },
    {
        "source": "SACC",
        "clause_type": "Commercial_Terms",
        "subtype": "Taxes_HST_GST",
        "clause_text": "All prices are exclusive of the Goods and Services Tax (GST) or Harmonized Sales Tax (HST), which shall be shown as a separate line item on all invoices. The Contractor is responsible for all other federal, provincial, and municipal taxes, duties, and levies applicable to the provision of the Work. Where the Contractor is a non-resident, applicable withholding tax under the Income Tax Act, RSC 1985, c 1 (5th Supp) shall apply.",
        "jurisdiction": "CA-Federal",
        "industry": "General",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "Federal",
        "clause_type": "Commercial_Terms",
        "subtype": "Currency_CAD",
        "clause_text": "All prices and payments under this Contract shall be in Canadian dollars (CAD). Where goods or services are sourced internationally, the Contractor shall bear all currency exchange risk. Invoices submitted in any currency other than Canadian dollars will be returned without processing.",
        "jurisdiction": "CA-Federal",
        "industry": "General",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "Federal",
        "clause_type": "Commercial_Terms",
        "subtype": "Travel_Expenses",
        "clause_text": "Travel and living expenses shall be reimbursed at cost, without markup, in accordance with the rates and allowances set out in the National Joint Council Travel Directive. All travel must be pre-authorized by the Technical Authority. Air travel shall be at economy class unless otherwise authorized. Claims must be supported by itemized receipts.",
        "jurisdiction": "CA-Federal",
        "industry": "Consulting",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "SACC",
        "clause_type": "Audit_Rights",
        "subtype": "Financial_Audit",
        "clause_text": "The Contractor shall maintain complete and accurate records and accounts of all costs and expenditures incurred under this Contract for a period of seven (7) years after final payment. Canada, the Auditor General of Canada, and their authorized representatives shall have the right, on reasonable notice, to inspect, audit, and copy any such records for the purpose of verifying charges and ensuring compliance with the Contract terms.",
        "jurisdiction": "CA-Federal",
        "industry": "General",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "Federal",
        "clause_type": "Commercial_Terms",
        "subtype": "Financial_Reporting",
        "clause_text": "The Contractor shall submit quarterly financial status reports within fifteen (15) business days of the end of each fiscal quarter. Reports shall include: actual expenditures to date, committed costs, forecast to completion, variance analysis, and a cash flow projection for the remaining Contract period.",
        "jurisdiction": "CA-Federal",
        "industry": "General",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "SACC",
        "clause_type": "Commercial_Terms",
        "subtype": "Performance_Guarantee",
        "clause_text": "The Contractor shall provide a performance guarantee in the form of an irrevocable standby letter of credit equal to fifteen percent (15%) of the total Contract value, drawn on a Canadian Schedule I or Schedule II bank. The guarantee shall remain in force until final acceptance of all deliverables and shall be returned to the Contractor within thirty (30) days thereafter.",
        "jurisdiction": "CA-Federal",
        "industry": "General",
        "risk_level": "Low",
        "is_standard": True,
    },
]
