"""Corporate governance + Fynk/ContractCodex commercial clauses."""

GOVERNANCE_CLAUSES = [
    # ── Corporate Governance ─────────────────────────────────
    {
        "source": "O'Brien_Forms",
        "clause_type": "Corporate_Governance",
        "subtype": "Board_Resolution",
        "clause_text": "BE IT RESOLVED THAT the Corporation is hereby authorized to enter into the Agreement described in the recitals hereto and to execute and deliver all documents and take all actions necessary or desirable to give effect thereto. The officers of the Corporation are hereby authorized and directed to execute the Agreement and all ancillary documents on behalf of the Corporation and to affix the corporate seal thereto.",
        "jurisdiction": "CA-ON",
        "industry": "General",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "O'Brien_Forms",
        "clause_type": "Corporate_Governance",
        "subtype": "Director_Indemnification",
        "clause_text": "The Corporation shall indemnify and hold harmless each director and officer of the Corporation from and against all costs, charges, and expenses, including legal fees, reasonably incurred in respect of any civil, criminal, or administrative action or proceeding to which the director or officer is made a party by reason of being a director or officer, provided they acted honestly and in good faith with a view to the best interests of the Corporation, as permitted by section 136 of the OBCA.",
        "jurisdiction": "CA-ON",
        "industry": "General",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "O'Brien_Forms",
        "clause_type": "Corporate_Governance",
        "subtype": "Articles_Amendment",
        "clause_text": "The shareholders of the Corporation hereby authorize the amendment of the articles of incorporation to: [describe amendment]. This special resolution has been approved by not less than two-thirds (2/3) of the votes cast by shareholders entitled to vote, in accordance with section 168 of the Business Corporations Act, RSO 1990, c B.16. The directors are authorized to file articles of amendment with the Ontario Ministry of Government and Consumer Services.",
        "jurisdiction": "CA-ON",
        "industry": "General",
        "risk_level": "Low",
        "is_standard": True,
    },
    # ── Fynk / ContractCodex Commercial Clauses ──────────────
    {
        "source": "Fynk",
        "clause_type": "Service_Agreement",
        "subtype": "Service_Description",
        "clause_text": "The Service Provider shall provide the Services described in Schedule A in a professional and workmanlike manner, consistent with generally accepted industry standards. The Service Provider shall allocate sufficient qualified personnel and resources to perform the Services within the timelines agreed upon. Any changes to the scope of Services shall be documented in a written change order signed by both parties.",
        "jurisdiction": "CA-ON",
        "industry": "General",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "Fynk",
        "clause_type": "Service_Agreement",
        "subtype": "Service_Credits",
        "clause_text": "If the Service Provider fails to meet the Service Levels set out in Schedule B, the Customer shall be entitled to service credits calculated as follows: for each 0.1% below the agreed availability target, a credit equal to 2% of the monthly service fee shall be applied to the next invoice. Service credits in any month shall not exceed 30% of the monthly fee. Service credits are the Customer's sole and exclusive remedy for failure to meet Service Levels.",
        "jurisdiction": "CA-ON",
        "industry": "IT",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "ContractCodex",
        "clause_type": "Distribution_Agreement",
        "subtype": "Exclusive_Distribution",
        "clause_text": "The Supplier hereby appoints the Distributor as its exclusive distributor for the Products in the Territory defined in Schedule A. During the term, the Supplier shall not sell the Products directly in the Territory or appoint any other distributor. The Distributor shall use commercially reasonable efforts to promote and sell the Products, maintain minimum annual purchase volumes as set out in Schedule B, and not sell products that compete directly with the Products.",
        "jurisdiction": "CA-ON",
        "industry": "General",
        "risk_level": "Medium",
        "is_standard": True,
    },
    {
        "source": "ContractCodex",
        "clause_type": "Licensing_Agreement",
        "subtype": "Software_License_Grant",
        "clause_text": "Subject to the terms of this Agreement and payment of the applicable fees, the Licensor hereby grants to the Licensee a non-exclusive, non-transferable, revocable licence to use the Software in object code form solely for the Licensee's internal business purposes. The Licensee shall not: (a) sublicense, sell, or distribute the Software; (b) modify, adapt, or create derivative works; (c) reverse-engineer, decompile, or disassemble the Software; or (d) use the Software for the benefit of any third party.",
        "jurisdiction": "CA-ON",
        "industry": "IT",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "Fynk",
        "clause_type": "Data_Processing",
        "subtype": "DPA_Controller_Processor",
        "clause_text": "The Processor shall process Personal Data only on documented instructions from the Controller and solely for the purposes of performing the Services. The Processor shall: (a) implement appropriate technical and organizational security measures; (b) not engage sub-processors without prior written consent; (c) assist the Controller with data subject access requests within five (5) business days; (d) notify the Controller within 24 hours of discovering a personal data breach; and (e) return or delete all Personal Data upon termination.",
        "jurisdiction": "CA-ON",
        "industry": "IT",
        "risk_level": "Medium",
        "is_standard": True,
    },
    {
        "source": "Fynk",
        "clause_type": "Auto_Renewal",
        "subtype": "Automatic_Renewal_Term",
        "clause_text": "This Agreement shall automatically renew for successive one (1) year periods upon expiry of the Initial Term unless either party provides written notice of non-renewal not less than ninety (90) days prior to the expiry of the then-current term. The fees for any renewal term shall be subject to adjustment by the Service Provider upon sixty (60) days' prior written notice, provided that any increase shall not exceed five percent (5%) of the fees in effect for the expiring term.",
        "jurisdiction": "CA-ON",
        "industry": "General",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "ContractCodex",
        "clause_type": "Exclusivity",
        "subtype": "Exclusivity_Period",
        "clause_text": "During the Exclusivity Period of sixty (60) days commencing on the date of this letter of intent, the Vendor shall not, directly or indirectly: (a) solicit, encourage, or accept any proposal from any other person relating to the sale of the Business or substantially all of its assets; (b) provide any confidential information to any third party; or (c) enter into any agreement or understanding relating to the foregoing. The Vendor shall immediately notify the Purchaser if it receives any such proposal.",
        "jurisdiction": "CA-ON",
        "industry": "General",
        "risk_level": "Medium",
        "is_standard": True,
    },
    {
        "source": "Fynk",
        "clause_type": "Payment_Terms",
        "subtype": "Late_Payment_Interest",
        "clause_text": "All invoices are due and payable within thirty (30) days of the invoice date. Overdue amounts shall bear interest at the lesser of: (a) 1.5% per month (18% per annum), compounded monthly; or (b) the maximum rate permitted by applicable law, including section 347 of the Criminal Code, RSC 1985, c C-46. The Service Provider may suspend Services upon fifteen (15) days' written notice if any invoice remains unpaid for more than sixty (60) days.",
        "jurisdiction": "CA-ON",
        "industry": "General",
        "risk_level": "Medium",
        "is_standard": True,
    },
    {
        "source": "ContractCodex",
        "clause_type": "Limitation_Liability",
        "subtype": "Aggregate_Cap",
        "clause_text": "The aggregate liability of the Service Provider under this Agreement, whether in contract, tort (including negligence), or otherwise, shall not exceed the total fees paid by the Customer in the twelve (12) months preceding the event giving rise to the claim. This limitation shall not apply to: (a) the Service Provider's indemnification obligations; (b) breaches of confidentiality; (c) fraud or wilful misconduct; or (d) liability for death or personal injury caused by negligence.",
        "jurisdiction": "CA-ON",
        "industry": "General",
        "risk_level": "Medium",
        "is_standard": True,
    },
]
