"""International procurement clauses — UNCITRAL, World Bank, EU, CETA, WTO GPA."""

INTERNATIONAL_CLAUSES = [
    {
        "source": "UNCITRAL",
        "clause_type": "International_Procurement",
        "subtype": "UNCITRAL_Model_Law",
        "clause_text": "This procurement is conducted in accordance with the principles of the UNCITRAL Model Law on Public Procurement (2011), ensuring transparency, competition, fairness, and economy in the procurement process. All bidders shall receive equal treatment and the evaluation criteria shall be disclosed in advance. The procuring entity shall maintain a record of the procurement proceedings.",
        "jurisdiction": "International",
        "industry": "General",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "World_Bank",
        "clause_type": "International_Procurement",
        "subtype": "World_Bank_Procurement",
        "clause_text": "This procurement is subject to the World Bank Procurement Regulations for IPF Borrowers (4th Edition, November 2020). The Contractor shall comply with the World Bank's Anti-Corruption Guidelines and Sanctions Framework. The World Bank reserves the right to audit all procurement activities and the Contractor shall maintain records for a minimum of seven (7) years following contract completion.",
        "jurisdiction": "International",
        "industry": "General",
        "risk_level": "Medium",
        "is_standard": True,
    },
    {
        "source": "EU_Directive",
        "clause_type": "International_Procurement",
        "subtype": "EU_Public_Procurement",
        "clause_text": "This procurement is conducted in accordance with Directive 2014/24/EU of the European Parliament on public procurement. The Contract Notice has been published in the Official Journal of the European Union (OJEU) via TED (Tenders Electronic Daily). All economic operators from EU and EEA member states are eligible to participate. Evaluation shall follow the most economically advantageous tender (MEAT) criteria.",
        "jurisdiction": "EU",
        "industry": "General",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "Federal",
        "clause_type": "International_Procurement",
        "subtype": "CETA_Compliance",
        "clause_text": "This procurement is subject to the Canada-European Union Comprehensive Economic and Trade Agreement (CETA), Chapter 19 — Government Procurement. Suppliers from EU member states shall be afforded national treatment and non-discrimination in accordance with CETA obligations. The procurement thresholds and procedures comply with Canada's commitments under CETA Annex 19-1.",
        "jurisdiction": "CA-Federal",
        "industry": "General",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "Federal",
        "clause_type": "International_Procurement",
        "subtype": "WTO_GPA",
        "clause_text": "This procurement is subject to the World Trade Organization Agreement on Government Procurement (GPA), as revised in 2012. Suppliers from GPA member states shall be afforded treatment no less favourable than domestic suppliers. The procurement notice has been published in accordance with WTO GPA transparency requirements and the applicable time limits for tendering have been observed.",
        "jurisdiction": "CA-Federal",
        "industry": "General",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "OECD",
        "clause_type": "International_Procurement",
        "subtype": "Anti_Bribery_OECD",
        "clause_text": "The Contractor certifies compliance with the OECD Convention on Combating Bribery of Foreign Public Officials in International Business Transactions and the corresponding Canadian implementing legislation, the Corruption of Foreign Public Officials Act, SC 1998, c 34. The Contractor shall maintain an anti-bribery compliance program including training, risk assessments, and reporting mechanisms.",
        "jurisdiction": "International",
        "industry": "General",
        "risk_level": "High",
        "is_standard": True,
    },
    {
        "source": "EU_Directive",
        "clause_type": "International_Procurement",
        "subtype": "Cross_Border_Data",
        "clause_text": "Where personal data is transferred between Canada and the European Union, such transfers shall comply with the EU General Data Protection Regulation (GDPR), Regulation (EU) 2016/679, and may only be made on the basis of an adequacy decision, standard contractual clauses approved by the European Commission, or binding corporate rules. The Contractor shall implement appropriate safeguards as required by Article 46 of the GDPR.",
        "jurisdiction": "International",
        "industry": "IT",
        "risk_level": "High",
        "is_standard": True,
    },
    {
        "source": "UNCITRAL",
        "clause_type": "Dispute_Resolution",
        "subtype": "International_Arbitration_ICC",
        "clause_text": "Any dispute arising out of or in connection with this Contract shall be finally settled under the Rules of Arbitration of the International Chamber of Commerce (ICC) by one or three arbitrators appointed in accordance with the said Rules. The seat of arbitration shall be Toronto, Canada. The language of the arbitration shall be English. The arbitral award shall be final and binding and may be enforced in any jurisdiction under the New York Convention.",
        "jurisdiction": "International",
        "industry": "General",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "World_Bank",
        "clause_type": "International_Procurement",
        "subtype": "Sustainable_Development",
        "clause_text": "The Contractor shall align its performance under this Contract with the United Nations Sustainable Development Goals (SDGs), in particular: Goal 8 (Decent Work and Economic Growth), Goal 12 (Responsible Consumption and Production), and Goal 16 (Peace, Justice, and Strong Institutions). The Contractor shall report annually on measures taken to advance these goals.",
        "jurisdiction": "International",
        "industry": "General",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "World_Bank",
        "clause_type": "International_Procurement",
        "subtype": "Human_Rights_Due_Diligence",
        "clause_text": "The Contractor shall conduct human rights due diligence in accordance with the UN Guiding Principles on Business and Human Rights (2011). The Contractor shall identify, prevent, mitigate, and account for adverse human rights impacts in its operations and supply chain. The Contractor shall establish a grievance mechanism accessible to affected stakeholders and shall remediate any adverse impacts identified.",
        "jurisdiction": "International",
        "industry": "General",
        "risk_level": "Medium",
        "is_standard": True,
    },
]
