"""Intellectual Property & Data clauses — IP ownership, data residency, breach, licensing."""

IP_DATA_CLAUSES = [
    {
        "source": "Ontario",
        "clause_type": "Intellectual_Property",
        "subtype": "Crown_Ownership",
        "clause_text": "All intellectual property created, developed, or first reduced to practice by the Contractor in the performance of this Contract shall vest in and be owned exclusively by Canada upon creation. The Contractor hereby assigns to Canada all right, title, and interest in such intellectual property and agrees to execute any further instruments required to perfect such assignment.",
        "jurisdiction": "CA-ON",
        "industry": "General",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "SACC",
        "clause_type": "Intellectual_Property",
        "subtype": "Background_IP_License",
        "clause_text": "The Contractor hereby grants to Canada a non-exclusive, irrevocable, royalty-free, worldwide licence to use, reproduce, modify, and distribute any pre-existing intellectual property of the Contractor that is incorporated into or necessary for Canada to use the Deliverables for the purposes contemplated by this Contract.",
        "jurisdiction": "CA-Federal",
        "industry": "General",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "Federal",
        "clause_type": "Intellectual_Property",
        "subtype": "Open_Source_Compliance",
        "clause_text": "The Contractor shall disclose all open-source software components incorporated into the Deliverables, including the applicable licence terms (GPL, MIT, Apache, etc.). The Contractor warrants that its use of open-source software does not create any obligation on Canada to release proprietary source code or pay royalties. A software bill of materials (SBOM) shall be provided with each release.",
        "jurisdiction": "CA-Federal",
        "industry": "IT",
        "risk_level": "Medium",
        "is_standard": True,
    },
    {
        "source": "Federal",
        "clause_type": "Data_Ownership",
        "subtype": "Crown_Data",
        "clause_text": "All data created, collected, or processed by the Contractor in the performance of this Contract is and shall remain the exclusive property of Canada. The Contractor shall not use such data for any purpose other than performing its obligations under this Contract and shall return or securely destroy all data within thirty (30) days of contract expiry or termination.",
        "jurisdiction": "CA-Federal",
        "industry": "General",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "Ontario",
        "clause_type": "Data_Portability",
        "subtype": "Data_Export",
        "clause_text": "The Contractor shall ensure that all data stored or processed under this Contract can be exported in a standard, machine-readable, non-proprietary format (CSV, JSON, XML, or equivalent) at any time during or after the Contract period. The Contractor shall not impose any technical barriers, fees, or delays that impede data portability.",
        "jurisdiction": "CA-ON",
        "industry": "IT",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "Federal",
        "clause_type": "Source_Code_Escrow",
        "subtype": "Escrow_Agreement",
        "clause_text": "Where the Deliverables include proprietary software, the Contractor shall deposit the source code, build scripts, and documentation with a mutually acceptable escrow agent. Canada shall be entitled to access the escrowed materials upon: (a) the Contractor's insolvency or bankruptcy; (b) the Contractor's failure to maintain or support the software; or (c) termination of the Contract for default.",
        "jurisdiction": "CA-Federal",
        "industry": "IT",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "SACC",
        "clause_type": "Software_Licensing",
        "subtype": "License_Grant",
        "clause_text": "Where the Contractor provides software under licence, the licence shall be non-exclusive, perpetual, irrevocable, and royalty-free for Canada's use for government purposes. The licence shall permit unlimited users within the federal government and shall not be subject to audit or compliance review by the Contractor without thirty (30) days advance notice.",
        "jurisdiction": "CA-Federal",
        "industry": "IT",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "Ontario",
        "clause_type": "Data_Residency",
        "subtype": "Canada_Only",
        "clause_text": "All data, including personal information and Protected B information, shall be stored, processed, and backed up exclusively within the geographic boundaries of Canada. The Contractor shall not transfer, store, or process any data outside Canada without the prior written consent of Canada. Cloud infrastructure must be hosted in Canadian data centres operated by providers with a Canadian presence.",
        "jurisdiction": "CA-ON",
        "industry": "IT",
        "risk_level": "High",
        "is_standard": True,
    },
    {
        "source": "Federal",
        "clause_type": "Data_Breach",
        "subtype": "Breach_Notification",
        "clause_text": "The Contractor shall notify Canada within twenty-four (24) hours of discovering any breach, unauthorized access, or loss of data processed under this Contract. The notification shall include the nature and scope of the breach, the data affected, actions taken to contain the breach, and a remediation plan. The Contractor shall bear all costs of breach response including notification to affected individuals, credit monitoring, and forensic investigation.",
        "jurisdiction": "CA-Federal",
        "industry": "IT",
        "risk_level": "High",
        "is_standard": True,
    },
    {
        "source": "Federal",
        "clause_type": "Data_Retention",
        "subtype": "Retention_Destruction",
        "clause_text": "The Contractor shall retain all data and records in accordance with the retention periods set out in Schedule C or as required by applicable law. Upon expiry of the retention period, or within thirty (30) days of written request by Canada, the Contractor shall securely destroy all data using methods consistent with ITSG-06 (Clearing and Declassifying Electronic Data Storage Devices) and provide a certificate of destruction.",
        "jurisdiction": "CA-Federal",
        "industry": "IT",
        "risk_level": "Medium",
        "is_standard": True,
    },
    {
        "source": "Ontario",
        "clause_type": "API_Access",
        "subtype": "Integration_Rights",
        "clause_text": "The Contractor shall provide fully documented RESTful API access to all data and functionality delivered under this Contract. APIs shall conform to the Government of Canada API Standards and shall be available at no additional cost for integration with other government systems. The Contractor shall maintain backward compatibility for a minimum of twelve (12) months following any API version change.",
        "jurisdiction": "CA-ON",
        "industry": "IT",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "Federal",
        "clause_type": "Technology_Transfer",
        "subtype": "Capability_Transfer",
        "clause_text": "The Contractor shall transfer sufficient technical knowledge to enable Canada's staff to independently operate, maintain, and enhance the Deliverables following the Contract period. Technology transfer shall include source code, configuration files, architecture documentation, runbooks, and a minimum of forty (40) hours of hands-on training.",
        "jurisdiction": "CA-Federal",
        "industry": "IT",
        "risk_level": "Low",
        "is_standard": True,
    },
]
