"""Litigation & Dispute clauses — settlement, release, consent, undertaking."""

LITIGATION_CLAUSES = [
    {
        "source": "O'Brien_Forms",
        "clause_type": "Settlement",
        "subtype": "Settlement_Agreement",
        "clause_text": "The parties agree to settle and finally resolve all claims, counterclaims, and disputes between them arising out of or relating to the matters described in Schedule A (the 'Dispute'), on the terms set out in this Agreement. In consideration of the settlement amount and mutual releases, each party shall forthwith discontinue any and all proceedings commenced in connection with the Dispute, with each party bearing its own costs.",
        "jurisdiction": "CA-ON",
        "industry": "General",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "O'Brien_Forms",
        "clause_type": "Release",
        "subtype": "Mutual_Release",
        "clause_text": "Each party hereby releases and forever discharges the other party, together with its directors, officers, employees, agents, successors, and assigns, from any and all actions, causes of action, claims, demands, damages, losses, costs, and expenses of every nature and kind whatsoever, whether known or unknown, which any party ever had, now has, or may hereafter have arising out of or in connection with the subject matter of this Agreement. This release shall be binding upon the heirs, executors, administrators, and assigns of each party.",
        "jurisdiction": "CA-ON",
        "industry": "General",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "O'Brien_Forms",
        "clause_type": "Release",
        "subtype": "Full_Final_Release_Employment",
        "clause_text": "In consideration of the severance package, the Employee releases and discharges the Employer from all claims arising from the employment relationship and its termination, including claims under the Employment Standards Act, 2000, the Human Rights Code, RSO 1990, c H.19, the Occupational Health and Safety Act, RSO 1990, c O.1, and the common law. The Employee confirms having had the opportunity to obtain independent legal advice and signing this Release voluntarily.",
        "jurisdiction": "CA-ON",
        "industry": "General",
        "risk_level": "Medium",
        "is_standard": True,
    },
    {
        "source": "ContractCodex",
        "clause_type": "Confidentiality",
        "subtype": "Settlement_Confidentiality",
        "clause_text": "The terms of this Settlement Agreement, including the settlement amount, are strictly confidential. Neither party shall disclose the terms of this Agreement to any third party except: (a) to their respective legal and financial advisors on a need-to-know basis; (b) as required by applicable law, regulation, or court order; or (c) as required for income tax reporting purposes. Any breach of this confidentiality provision shall entitle the non-breaching party to liquidated damages of $50,000.",
        "jurisdiction": "CA-ON",
        "industry": "General",
        "risk_level": "Medium",
        "is_standard": True,
    },
    {
        "source": "O'Brien_Forms",
        "clause_type": "Consent",
        "subtype": "Consent_to_Judgment",
        "clause_text": "The Defendant hereby consents to judgment being entered against it in the amount of [AMOUNT], inclusive of prejudgment interest and costs, in full and final satisfaction of the Plaintiff's claim in Court File No. [NUMBER]. This consent shall be filed with the Superior Court of Justice and the judgment may be enforced in accordance with the Courts of Justice Act, RSO 1990, c C.43, and the Rules of Civil Procedure.",
        "jurisdiction": "CA-ON",
        "industry": "General",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "O'Brien_Forms",
        "clause_type": "Undertaking",
        "subtype": "Solicitors_Undertaking",
        "clause_text": "The undersigned solicitor hereby undertakes to: (a) hold the documents and funds in trust pending completion of the transaction; (b) not release the funds until all conditions have been satisfied; (c) register the transfer/charge on title within two (2) business days of closing; and (d) report to the parties upon completion. This undertaking is given in accordance with the Rules of Professional Conduct of the Law Society of Ontario and is personally binding upon the undersigned solicitor.",
        "jurisdiction": "CA-ON",
        "industry": "General",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "Fynk",
        "clause_type": "Non_Disparagement",
        "subtype": "Mutual_Non_Disparagement",
        "clause_text": "Each party agrees not to make, publish, or cause to be made or published any statement, oral or written, that disparages, defames, or damages the reputation of the other party or its directors, officers, or employees. Nothing in this clause shall prevent either party from providing truthful testimony or information when required by law, regulation, or legal process.",
        "jurisdiction": "CA-ON",
        "industry": "General",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "ContractCodex",
        "clause_type": "Limitation_Period",
        "subtype": "Contractual_Limitation",
        "clause_text": "No action or proceeding arising out of or related to this Agreement may be commenced more than two (2) years after the cause of action is discovered or ought to have been discovered, in accordance with the Limitations Act, 2002, SO 2002, c 24, Schedule B. The parties agree that this limitation period is reasonable and shall apply notwithstanding any shorter or longer period that might otherwise apply.",
        "jurisdiction": "CA-ON",
        "industry": "General",
        "risk_level": "Low",
        "is_standard": True,
    },
]
