"""Procurement process clauses — bonds, evaluation, conflict of interest, etc."""

PROCUREMENT_CLAUSES = [
    {
        "source": "SACC",
        "clause_type": "Bid_Bond",
        "subtype": "Financial_Security",
        "clause_text": "The Bidder shall provide a bid bond or irrevocable standby letter of credit in the amount of ten percent (10%) of the total bid price, issued by a surety licensed to operate in Canada and acceptable to Canada. The bid bond shall remain valid for a minimum of sixty (60) days following bid closing.",
        "jurisdiction": "CA-Federal",
        "industry": "Construction",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "SACC",
        "clause_type": "Performance_Bond",
        "subtype": "Financial_Security",
        "clause_text": "Within fourteen (14) calendar days of contract award, the Contractor shall deliver to Canada a performance bond in the amount of fifty percent (50%) of the Contract Price, issued by a surety licensed in Canada and listed on the Treasury Board list of approved sureties. The bond shall remain in force until one (1) year after the date of substantial completion.",
        "jurisdiction": "CA-Federal",
        "industry": "Construction",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "SACC",
        "clause_type": "Labour_Material_Bond",
        "subtype": "Financial_Security",
        "clause_text": "The Contractor shall deliver a labour and material payment bond in the amount of fifty percent (50%) of the Contract Price to protect subcontractors and suppliers. The bond shall be issued by a surety company approved by the Treasury Board of Canada and shall remain valid for the duration of the Contract plus the applicable statutory lien period.",
        "jurisdiction": "CA-Federal",
        "industry": "Construction",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "SACC",
        "clause_type": "Bid_Evaluation",
        "subtype": "Evaluation_Criteria",
        "clause_text": "Bids will be evaluated on the basis of the highest combined rating of technical merit and price using a weighting of 70% technical and 30% price. Only bids that meet all mandatory technical requirements and achieve a minimum score of 70% on the rated technical criteria will be considered for financial evaluation.",
        "jurisdiction": "CA-Federal",
        "industry": "General",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "SACC",
        "clause_type": "Conflict_of_Interest",
        "subtype": "Disclosure_Obligation",
        "clause_text": "The Contractor shall not provide any services to any person or entity where such services could give rise to a real, potential, or apparent conflict of interest in relation to the Work under this Contract. The Contractor shall promptly disclose to Canada any situation that may constitute a conflict of interest and Canada shall determine, at its sole discretion, whether a conflict exists and the appropriate remedy.",
        "jurisdiction": "CA-Federal",
        "industry": "General",
        "risk_level": "Medium",
        "is_standard": True,
    },
    {
        "source": "SACC",
        "clause_type": "Subcontracting",
        "subtype": "Consent_Required",
        "clause_text": "The Contractor shall not subcontract any part of the Work without the prior written consent of the Contracting Authority. The Contractor shall remain fully responsible for the performance of all subcontracted work as if such work were performed by the Contractor directly. Subcontracting does not relieve the Contractor of any obligation under this Contract.",
        "jurisdiction": "CA-Federal",
        "industry": "General",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "Federal",
        "clause_type": "Joint_Venture",
        "subtype": "JV_Requirements",
        "clause_text": "Where a joint venture is proposed, each member of the joint venture shall be jointly and severally liable for the performance of the entire Contract. The joint venture shall designate a lead member authorized to act on behalf of all members. Any change to the composition of the joint venture after contract award requires the prior written approval of Canada.",
        "jurisdiction": "CA-Federal",
        "industry": "General",
        "risk_level": "Medium",
        "is_standard": True,
    },
    {
        "source": "Federal",
        "clause_type": "Canadian_Content",
        "subtype": "Domestic_Preference",
        "clause_text": "This procurement is subject to the Canadian Content Policy. The Contractor certifies that the goods and services delivered under this Contract will meet the Canadian Content requirements, meaning not less than eighty percent (80%) of the total bid price shall represent Canadian goods and services as defined in the Supply Manual.",
        "jurisdiction": "CA-Federal",
        "industry": "General",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "Federal",
        "clause_type": "Indigenous_Procurement",
        "subtype": "PSAB_Set_Aside",
        "clause_text": "This procurement is set aside under the Procurement Strategy for Aboriginal Business (PSAB). To be eligible, bidders must be Indigenous businesses as defined by Indigenous Services Canada, meaning at least 51% owned and controlled by Indigenous peoples, with at least 33% of the workforce being Indigenous. The Contractor shall maintain compliance with PSAB requirements throughout the Contract term.",
        "jurisdiction": "CA-Federal",
        "industry": "General",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "Federal",
        "clause_type": "Green_Procurement",
        "subtype": "Environmental_Requirements",
        "clause_text": "The Contractor shall comply with the Government of Canada's Policy on Green Procurement and the Federal Sustainable Development Strategy. All deliverables shall minimize environmental impact, including the use of recycled or recyclable materials, energy-efficient equipment, and reduced packaging. The Contractor shall report on carbon footprint and waste reduction measures as part of quarterly reporting.",
        "jurisdiction": "CA-Federal",
        "industry": "General",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "SACC",
        "clause_type": "Security_Clearance",
        "subtype": "Personnel_Screening",
        "clause_text": "The Contractor's personnel who require access to protected or classified information, assets, or sensitive work sites must hold a valid security clearance at the level required (Reliability Status, Secret, or Top Secret) issued by the Canadian Industrial Security Directorate (CISD). The Contractor shall not permit any individual to access such information without the required clearance.",
        "jurisdiction": "CA-Federal",
        "industry": "General",
        "risk_level": "Medium",
        "is_standard": True,
    },
    {
        "source": "Federal",
        "clause_type": "Integrity_Provisions",
        "subtype": "Ineligibility_Suspension",
        "clause_text": "The Contractor certifies that neither the Contractor nor any of its affiliates has been convicted of or charged with offences listed under the Ineligibility and Suspension Policy, including fraud, bribery, collusion, bid-rigging, money laundering, tax evasion, or trafficking. The Contractor shall immediately disclose any change in status and understands that a breach may result in contract termination and a period of ineligibility.",
        "jurisdiction": "CA-Federal",
        "industry": "General",
        "risk_level": "High",
        "is_standard": True,
    },
    # ── CFTA / Competition Act / CITT ────────────────────────
    {
        "source": "Federal",
        "clause_type": "Trade_Agreement",
        "subtype": "CFTA_Obligations",
        "clause_text": "This procurement is subject to the Canadian Free Trade Agreement (CFTA), Chapter 5 — Government Procurement. In accordance with CFTA Article 504, all Canadian suppliers shall be afforded equal access and non-discriminatory treatment. The procurement thresholds, time limits, and procedures comply with Canada's obligations under the CFTA, including the requirement to publish procurement notices on a single electronic tendering system accessible to all Canadian suppliers.",
        "jurisdiction": "CA-Federal",
        "industry": "General",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "Federal",
        "clause_type": "Trade_Agreement",
        "subtype": "CFTA_Non_Discrimination",
        "clause_text": "Pursuant to CFTA Article 503, the procuring entity shall not discriminate against goods, services, or suppliers of any Canadian province or territory. Technical specifications shall not be prepared, adopted, or applied with the purpose or effect of creating unnecessary obstacles to internal trade. Where reference is made to specific standards, the words 'or equivalent' shall be included.",
        "jurisdiction": "CA-Federal",
        "industry": "General",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "Federal",
        "clause_type": "Trade_Agreement",
        "subtype": "CFTA_Bid_Challenge",
        "clause_text": "Any supplier that believes a procurement covered by the CFTA has not been conducted in accordance with Chapter 5 may file a complaint with the Canadian International Trade Tribunal (CITT) within ten (10) working days of when the basis of the complaint became known or reasonably should have become known, pursuant to CFTA Article 517 and the Canadian International Trade Tribunal Procurement Inquiry Regulations, SOR/93-602.",
        "jurisdiction": "CA-Federal",
        "industry": "General",
        "risk_level": "Medium",
        "is_standard": True,
    },
    {
        "source": "Federal",
        "clause_type": "Trade_Agreement",
        "subtype": "CFTA_Limited_Tendering",
        "clause_text": "Limited tendering (sole-source or non-competitive procurement) may only be used in circumstances permitted under CFTA Article 513, including: (a) no responsive bids received in open tendering; (b) only one supplier capable of performing the work due to exclusive rights; (c) extreme urgency; (d) procurement from an original supplier for additional goods or services; or (e) procurement below the applicable CFTA threshold. The procuring entity shall maintain a record justifying the use of limited tendering.",
        "jurisdiction": "CA-Federal",
        "industry": "General",
        "risk_level": "Medium",
        "is_standard": True,
    },
    {
        "source": "Federal",
        "clause_type": "Trade_Agreement",
        "subtype": "CFTA_Procurement_Thresholds",
        "clause_text": "This procurement is subject to CFTA Chapter 5 as the estimated value exceeds the applicable threshold: $30,300 CAD for goods, $121,200 CAD for services, and $303,000 CAD for construction (2024-2025 values, adjusted biennially). The procuring entity shall not divide a procurement into separate contracts or use valuation methods to avoid the application of CFTA obligations.",
        "jurisdiction": "CA-Federal",
        "industry": "General",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "Federal",
        "clause_type": "Competition_Law",
        "subtype": "Competition_Act_Bid_Rigging",
        "clause_text": "The Contractor certifies that it has not, directly or indirectly, engaged in bid-rigging as defined in section 47 of the Competition Act, RSC 1985, c C-34. Bid-rigging is a criminal offence carrying a maximum penalty of imprisonment for up to fourteen (14) years and/or a fine at the discretion of the court. The Contractor shall not enter into any agreement or arrangement with other bidders regarding the submission or withdrawal of bids, price levels, or allocation of contracts.",
        "jurisdiction": "CA-Federal",
        "industry": "General",
        "risk_level": "High",
        "is_standard": True,
    },
    {
        "source": "Federal",
        "clause_type": "Competition_Law",
        "subtype": "Competition_Act_Conspiracy",
        "clause_text": "The Contractor certifies compliance with section 45 of the Competition Act, RSC 1985, c C-34, and represents that it has not conspired, agreed, or arranged with any competitor to fix prices, allocate markets or customers, or restrict the supply of goods or services in relation to this procurement. A breach of this certification shall constitute grounds for immediate termination of the Contract for default and may result in debarment under the Ineligibility and Suspension Policy.",
        "jurisdiction": "CA-Federal",
        "industry": "General",
        "risk_level": "High",
        "is_standard": True,
    },
    {
        "source": "Federal",
        "clause_type": "Competition_Law",
        "subtype": "Competition_Act_Deceptive_Practices",
        "clause_text": "The Contractor represents that no false or misleading representations have been made in connection with this procurement, in accordance with sections 52 and 74.01 of the Competition Act, RSC 1985, c C-34. The Contractor warrants that all representations made in its bid or proposal, including qualifications of personnel, past performance, and financial capacity, are truthful and not misleading in any material respect.",
        "jurisdiction": "CA-Federal",
        "industry": "General",
        "risk_level": "High",
        "is_standard": True,
    },
    {
        "source": "Federal",
        "clause_type": "Competition_Law",
        "subtype": "Competition_Bureau_Cooperation",
        "clause_text": "The Contractor acknowledges that the Competition Bureau of Canada may investigate suspected bid-rigging, price-fixing, or other anti-competitive conduct in government procurement. The Contractor shall cooperate fully with any investigation by the Competition Bureau and shall preserve all records relating to this procurement process. The Contractor shall immediately report to the Contracting Authority any conduct by competitors that the Contractor reasonably believes may constitute a violation of the Competition Act.",
        "jurisdiction": "CA-Federal",
        "industry": "General",
        "risk_level": "Medium",
        "is_standard": True,
    },
    {
        "source": "Federal",
        "clause_type": "Procurement_Oversight",
        "subtype": "CITT_Procurement_Review",
        "clause_text": "This procurement is subject to review by the Canadian International Trade Tribunal (CITT) under the Canadian International Trade Tribunal Act, RSC 1985, c 47 (4th Supp). Any potential supplier who believes the procurement has not been conducted in accordance with the applicable trade agreements (CFTA, CETA, WTO GPA, CPTPP) may file a complaint with the CITT. The CITT may make recommendations including re-evaluation, re-tendering, or award of compensation for lost profit or bid preparation costs.",
        "jurisdiction": "CA-Federal",
        "industry": "General",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "Federal",
        "clause_type": "Procurement_Oversight",
        "subtype": "CITT_Inquiry_Process",
        "clause_text": "Complaints to the Canadian International Trade Tribunal must be filed within ten (10) working days of when the complainant knew or reasonably should have known of the basis for the complaint, in accordance with the CITT Procurement Inquiry Regulations, SOR/93-602. The CITT shall determine within five (5) working days whether to conduct an inquiry. If an inquiry is initiated before contract award, the procuring entity shall delay award for the duration of the inquiry unless urgent operational requirements justify proceeding.",
        "jurisdiction": "CA-Federal",
        "industry": "General",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "Federal",
        "clause_type": "Procurement_Oversight",
        "subtype": "CITT_Remedies",
        "clause_text": "Where the CITT determines that a procurement was not conducted in accordance with applicable trade agreement obligations, the Tribunal may recommend that the procuring entity: (a) re-evaluate the bids; (b) terminate the contract and re-tender; (c) award the contract to the complainant; or (d) pay compensation equal to the complainant's reasonable bid preparation costs or, where appropriate, lost profits. The Government of Canada shall implement CITT recommendations within the time specified by the Tribunal.",
        "jurisdiction": "CA-Federal",
        "industry": "General",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "Federal",
        "clause_type": "Procurement_Oversight",
        "subtype": "Office_Procurement_Ombudsman",
        "clause_text": "Suppliers may also raise procurement-related concerns with the Office of the Procurement Ombudsman (OPO) established under the Department of Public Works and Government Services Act, RSC 1985, c P-38.2, section 22.1. The OPO reviews procurement practices, investigates complaints from suppliers regarding contract awards below the CITT threshold, and may make non-binding recommendations to improve fairness and transparency in federal procurement.",
        "jurisdiction": "CA-Federal",
        "industry": "General",
        "risk_level": "Low",
        "is_standard": True,
    },
]
