"""Procurement process clauses — bonds, evaluation, conflict of interest, etc."""

PROCUREMENT_CLAUSES = [
    {
        "source": "SACC",
        "clause_type": "Bid_Bond",
        "subtype": "Financial_Security",
        "clause_text": "The Bidder shall provide a bid bond or irrevocable standby letter of credit in the amount of ten percent (10%) of the total bid price, issued by a surety licensed to operate in Canada and acceptable to Canada. The bid bond shall remain valid for a minimum of sixty (60) days following bid closing.",
        "jurisdiction": "CA-Federal",
        "industry": "Construction",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "SACC",
        "clause_type": "Performance_Bond",
        "subtype": "Financial_Security",
        "clause_text": "Within fourteen (14) calendar days of contract award, the Contractor shall deliver to Canada a performance bond in the amount of fifty percent (50%) of the Contract Price, issued by a surety licensed in Canada and listed on the Treasury Board list of approved sureties. The bond shall remain in force until one (1) year after the date of substantial completion.",
        "jurisdiction": "CA-Federal",
        "industry": "Construction",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "SACC",
        "clause_type": "Labour_Material_Bond",
        "subtype": "Financial_Security",
        "clause_text": "The Contractor shall deliver a labour and material payment bond in the amount of fifty percent (50%) of the Contract Price to protect subcontractors and suppliers. The bond shall be issued by a surety company approved by the Treasury Board of Canada and shall remain valid for the duration of the Contract plus the applicable statutory lien period.",
        "jurisdiction": "CA-Federal",
        "industry": "Construction",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "SACC",
        "clause_type": "Bid_Evaluation",
        "subtype": "Evaluation_Criteria",
        "clause_text": "Bids will be evaluated on the basis of the highest combined rating of technical merit and price using a weighting of 70% technical and 30% price. Only bids that meet all mandatory technical requirements and achieve a minimum score of 70% on the rated technical criteria will be considered for financial evaluation.",
        "jurisdiction": "CA-Federal",
        "industry": "General",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "SACC",
        "clause_type": "Conflict_of_Interest",
        "subtype": "Disclosure_Obligation",
        "clause_text": "The Contractor shall not provide any services to any person or entity where such services could give rise to a real, potential, or apparent conflict of interest in relation to the Work under this Contract. The Contractor shall promptly disclose to Canada any situation that may constitute a conflict of interest and Canada shall determine, at its sole discretion, whether a conflict exists and the appropriate remedy.",
        "jurisdiction": "CA-Federal",
        "industry": "General",
        "risk_level": "Medium",
        "is_standard": True,
    },
    {
        "source": "SACC",
        "clause_type": "Subcontracting",
        "subtype": "Consent_Required",
        "clause_text": "The Contractor shall not subcontract any part of the Work without the prior written consent of the Contracting Authority. The Contractor shall remain fully responsible for the performance of all subcontracted work as if such work were performed by the Contractor directly. Subcontracting does not relieve the Contractor of any obligation under this Contract.",
        "jurisdiction": "CA-Federal",
        "industry": "General",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "Federal",
        "clause_type": "Joint_Venture",
        "subtype": "JV_Requirements",
        "clause_text": "Where a joint venture is proposed, each member of the joint venture shall be jointly and severally liable for the performance of the entire Contract. The joint venture shall designate a lead member authorized to act on behalf of all members. Any change to the composition of the joint venture after contract award requires the prior written approval of Canada.",
        "jurisdiction": "CA-Federal",
        "industry": "General",
        "risk_level": "Medium",
        "is_standard": True,
    },
    {
        "source": "Federal",
        "clause_type": "Canadian_Content",
        "subtype": "Domestic_Preference",
        "clause_text": "This procurement is subject to the Canadian Content Policy. The Contractor certifies that the goods and services delivered under this Contract will meet the Canadian Content requirements, meaning not less than eighty percent (80%) of the total bid price shall represent Canadian goods and services as defined in the Supply Manual.",
        "jurisdiction": "CA-Federal",
        "industry": "General",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "Federal",
        "clause_type": "Indigenous_Procurement",
        "subtype": "PSAB_Set_Aside",
        "clause_text": "This procurement is set aside under the Procurement Strategy for Aboriginal Business (PSAB). To be eligible, bidders must be Indigenous businesses as defined by Indigenous Services Canada, meaning at least 51% owned and controlled by Indigenous peoples, with at least 33% of the workforce being Indigenous. The Contractor shall maintain compliance with PSAB requirements throughout the Contract term.",
        "jurisdiction": "CA-Federal",
        "industry": "General",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "Federal",
        "clause_type": "Green_Procurement",
        "subtype": "Environmental_Requirements",
        "clause_text": "The Contractor shall comply with the Government of Canada's Policy on Green Procurement and the Federal Sustainable Development Strategy. All deliverables shall minimize environmental impact, including the use of recycled or recyclable materials, energy-efficient equipment, and reduced packaging. The Contractor shall report on carbon footprint and waste reduction measures as part of quarterly reporting.",
        "jurisdiction": "CA-Federal",
        "industry": "General",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "SACC",
        "clause_type": "Security_Clearance",
        "subtype": "Personnel_Screening",
        "clause_text": "The Contractor's personnel who require access to protected or classified information, assets, or sensitive work sites must hold a valid security clearance at the level required (Reliability Status, Secret, or Top Secret) issued by the Canadian Industrial Security Directorate (CISD). The Contractor shall not permit any individual to access such information without the required clearance.",
        "jurisdiction": "CA-Federal",
        "industry": "General",
        "risk_level": "Medium",
        "is_standard": True,
    },
    {
        "source": "Federal",
        "clause_type": "Integrity_Provisions",
        "subtype": "Ineligibility_Suspension",
        "clause_text": "The Contractor certifies that neither the Contractor nor any of its affiliates has been convicted of or charged with offences listed under the Ineligibility and Suspension Policy, including fraud, bribery, collusion, bid-rigging, money laundering, tax evasion, or trafficking. The Contractor shall immediately disclose any change in status and understands that a breach may result in contract termination and a period of ineligibility.",
        "jurisdiction": "CA-Federal",
        "industry": "General",
        "risk_level": "High",
        "is_standard": True,
    },
]
