"""Real property clauses — leases, purchase/sale, easements, mortgage, liens."""

REALPROPERTY_CLAUSES = [
    {
        "source": "O'Brien_Forms",
        "clause_type": "Lease",
        "subtype": "Commercial_Lease_Term",
        "clause_text": "The Landlord hereby leases to the Tenant the Premises described in Schedule A for a term of five (5) years commencing on the Commencement Date. The Tenant shall have the option to renew for two (2) additional terms of five (5) years each, provided the Tenant gives written notice of its intention to renew not less than six (6) months prior to the expiry of the then-current term and is not in default under this Lease at the time of such notice.",
        "jurisdiction": "CA-ON",
        "industry": "General",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "O'Brien_Forms",
        "clause_type": "Lease",
        "subtype": "Net_Lease_Additional_Rent",
        "clause_text": "In addition to Base Rent, the Tenant shall pay as Additional Rent its Proportionate Share of all Operating Costs, realty taxes, and insurance premiums for the Building, calculated annually and payable in equal monthly installments. Operating Costs include all costs incurred by the Landlord in operating, maintaining, repairing, and managing the Building and common areas. The Landlord shall provide an annual reconciliation statement within ninety (90) days after each fiscal year.",
        "jurisdiction": "CA-ON",
        "industry": "General",
        "risk_level": "Medium",
        "is_standard": True,
    },
    {
        "source": "ContractCodex",
        "clause_type": "Lease",
        "subtype": "Tenant_Improvements",
        "clause_text": "The Tenant may make improvements, alterations, or additions to the Premises only with the prior written consent of the Landlord, which shall not be unreasonably withheld. All improvements shall be performed by licensed contractors with appropriate insurance, in compliance with the Ontario Building Code and all applicable laws. Leasehold improvements shall become the property of the Landlord upon installation unless otherwise agreed in writing.",
        "jurisdiction": "CA-ON",
        "industry": "General",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "O'Brien_Forms",
        "clause_type": "Purchase_Sale",
        "subtype": "APS_Residential",
        "clause_text": "The Buyer agrees to purchase from the Seller the property municipally known as [Address] (the 'Property') for the Purchase Price, subject to the terms and conditions herein. The Buyer shall have until the Requisition Date to examine title and satisfy itself that there are no outstanding work orders or deficiency notices affecting the Property. If the Buyer is not satisfied, in its sole and absolute discretion, the Buyer may terminate this Agreement and the deposit shall be returned in full.",
        "jurisdiction": "CA-ON",
        "industry": "General",
        "risk_level": "Medium",
        "is_standard": True,
    },
    {
        "source": "O'Brien_Forms",
        "clause_type": "Purchase_Sale",
        "subtype": "Title_Warranties",
        "clause_text": "The Seller represents and warrants that: (a) the Seller has good and marketable title to the Property free from all encumbrances except as disclosed; (b) there are no outstanding work orders, deficiency notices, or compliance orders affecting the Property; (c) the Property is not subject to any agreement of purchase and sale or option; (d) the Seller has the legal right and authority to sell the Property; and (e) the representations and warranties shall survive closing for a period of two (2) years.",
        "jurisdiction": "CA-ON",
        "industry": "General",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "O'Brien_Forms",
        "clause_type": "Easement",
        "subtype": "Right_of_Way",
        "clause_text": "The Grantor hereby grants to the Grantee, its successors and assigns, a perpetual and non-exclusive easement and right-of-way over, under, across, and upon the lands described in Schedule A for the purpose of access, ingress, and egress to and from the Dominant Tenement. The Grantee shall maintain the easement area in good repair and shall not interfere with the Grantor's reasonable use of the Servient Tenement. This easement shall run with the land and be binding upon successors in title.",
        "jurisdiction": "CA-ON",
        "industry": "General",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "O'Brien_Forms",
        "clause_type": "Mortgage",
        "subtype": "Standard_Charge_Terms",
        "clause_text": "The Chargor hereby charges the Property as security for the payment of the Principal Amount and interest thereon at the rate specified, payable in equal monthly installments of blended principal and interest. Upon default in any payment for a period of fifteen (15) days, the entire principal balance and accrued interest shall, at the option of the Chargee, become immediately due and payable. The Chargor shall maintain the Property in good repair, pay all taxes, and maintain fire insurance with the Chargee named as loss payee.",
        "jurisdiction": "CA-ON",
        "industry": "General",
        "risk_level": "Medium",
        "is_standard": True,
    },
    {
        "source": "O'Brien_Forms",
        "clause_type": "Construction_Lien",
        "subtype": "Builders_Lien_Holdback",
        "clause_text": "The Owner shall retain a holdback of ten percent (10%) of the price of the services or materials as required under the Construction Act, RSO 1990, c C.30, section 22. The holdback shall be retained from each progress payment and released to the Contractor sixty (60) days after the publication of a certificate of substantial performance or completion, provided no liens have been preserved against the holdback within the prescribed time periods.",
        "jurisdiction": "CA-ON",
        "industry": "Construction",
        "risk_level": "Low",
        "is_standard": True,
    },
]
