"""Risk & Liability clauses — indemnification, limitation of liability, insurance."""

RISK_CLAUSES = [
    {
        "source": "Ontario",
        "clause_type": "Risk_Allocation",
        "subtype": "Indemnity_Standard",
        "clause_text": "The Contractor shall indemnify and hold harmless Canada, its officers, employees, and agents from and against any and all claims, damages, losses, costs, and expenses arising out of or related to: (a) any breach by the Contractor of this Contract; (b) any negligent or wrongful act or omission of the Contractor; or (c) any infringement of intellectual property rights by the Contractor.",
        "jurisdiction": "CA-ON",
        "industry": "General",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "SACC",
        "clause_type": "Risk_Allocation",
        "subtype": "IP_Indemnification",
        "clause_text": "The Contractor shall defend, indemnify, and hold harmless Canada from any third-party claim alleging that the Deliverables or Canada's use thereof infringes any patent, copyright, trademark, or trade secret. The Contractor's obligation is conditional on Canada providing prompt written notice, granting the Contractor sole control of the defence, and providing reasonable assistance at the Contractor's expense.",
        "jurisdiction": "CA-Federal",
        "industry": "General",
        "risk_level": "Medium",
        "is_standard": True,
    },
    {
        "source": "SACC",
        "clause_type": "Risk_Allocation",
        "subtype": "Mutual_Limitation_Liability",
        "clause_text": "Neither party shall be liable to the other for any indirect, incidental, special, exemplary, or consequential damages, including loss of revenue, loss of profits, loss of data, or loss of goodwill. Each party's aggregate liability arising out of this Contract shall not exceed the total fees paid or payable in the twelve (12) months preceding the event giving rise to the claim.",
        "jurisdiction": "CA-Federal",
        "industry": "General",
        "risk_level": "Medium",
        "is_standard": True,
    },
    {
        "source": "SACC",
        "clause_type": "Risk_Allocation",
        "subtype": "Liability_Cap_Carveouts",
        "clause_text": "The limitations on liability shall not apply to: (a) fraud or wilful misconduct; (b) gross negligence; (c) indemnification obligations under this Contract; (d) breaches of confidentiality; (e) breaches of intellectual property provisions; or (f) any liability that cannot be limited by applicable law including the Crown Liability and Proceedings Act, RSC 1985, c C-50.",
        "jurisdiction": "CA-Federal",
        "industry": "General",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "SACC",
        "clause_type": "Insurance",
        "subtype": "Professional_Liability",
        "clause_text": "The Contractor shall obtain and maintain professional liability (errors and omissions) insurance with a minimum limit of two million dollars ($2,000,000) per occurrence and in the aggregate. The policy shall be maintained for the duration of the Contract and for a period of not less than two (2) years following completion of the Work. Canada shall be named as an additional insured.",
        "jurisdiction": "CA-Federal",
        "industry": "Consulting",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "SACC",
        "clause_type": "Insurance",
        "subtype": "Commercial_General_Liability",
        "clause_text": "The Contractor shall obtain and maintain commercial general liability insurance with a minimum limit of five million dollars ($5,000,000) per occurrence, covering bodily injury, property damage, personal injury, and products and completed operations. The policy shall include a cross-liability clause and Canada shall be named as an additional insured.",
        "jurisdiction": "CA-Federal",
        "industry": "General",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "Ontario",
        "clause_type": "Insurance",
        "subtype": "Cyber_Liability",
        "clause_text": "The Contractor shall obtain and maintain cyber liability insurance with a minimum limit of one million dollars ($1,000,000) covering data breach response costs, network security liability, media liability, regulatory fines and penalties, and cyber extortion. The policy shall cover both first-party and third-party losses arising from a cyber security incident.",
        "jurisdiction": "CA-ON",
        "industry": "IT",
        "risk_level": "Medium",
        "is_standard": True,
    },
    {
        "source": "SACC",
        "clause_type": "Insurance",
        "subtype": "Workers_Compensation",
        "clause_text": "The Contractor shall comply with all applicable provincial and territorial workers' compensation legislation and shall maintain coverage for all its employees and subcontractors engaged in the Work. The Contractor shall provide a valid clearance certificate from the applicable Workers' Safety and Insurance Board (WSIB) or equivalent authority prior to commencing work.",
        "jurisdiction": "CA-Federal",
        "industry": "General",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "Ontario",
        "clause_type": "Insurance",
        "subtype": "Errors_Omissions",
        "clause_text": "For professional services engagements, the Contractor shall maintain errors and omissions insurance with a minimum limit of two million dollars ($2,000,000) per claim, covering negligent acts, errors, or omissions in the performance of professional services under this Contract. The policy shall have a retroactive date no later than the Contract commencement date.",
        "jurisdiction": "CA-ON",
        "industry": "Consulting",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "SACC",
        "clause_type": "Insurance",
        "subtype": "Product_Liability",
        "clause_text": "Where the Work involves the supply of goods or manufactured products, the Contractor shall maintain product liability insurance with a minimum limit of five million dollars ($5,000,000) per occurrence covering damages arising from defects in products supplied under this Contract. Coverage shall extend to the completed operations period for a minimum of two (2) years following final delivery.",
        "jurisdiction": "CA-Federal",
        "industry": "General",
        "risk_level": "Low",
        "is_standard": True,
    },
]
