"""Scope & Performance clauses — SOW, SLAs, acceptance, warranty, reporting."""

SCOPE_CLAUSES = [
    {
        "source": "Ontario",
        "clause_type": "Deliverables",
        "subtype": "Tangible_Deliverables",
        "clause_text": "The Contractor shall deliver all services and outputs in accordance with the specifications set out in this Scope of Work, including but not limited to reports, documentation, and system implementations, within the timelines specified in Schedule A.",
        "jurisdiction": "CA-ON",
        "industry": "General",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "Ontario",
        "clause_type": "Timeline_Milestones",
        "subtype": "Deadlines",
        "clause_text": "All deliverables must be completed within the timelines specified in Schedule A, and no later than 30 calendar days from the commencement date, unless otherwise approved in writing by Canada.",
        "jurisdiction": "CA-ON",
        "industry": "General",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "SACC",
        "clause_type": "Acceptance_Closure",
        "subtype": "Acceptance_Testing",
        "clause_text": "Canada shall have fifteen (15) business days following receipt of each deliverable to conduct acceptance testing in accordance with the acceptance criteria set out in Schedule A. Canada shall provide written notice of acceptance or rejection with specific deficiencies identified. The Contractor shall correct all deficiencies within ten (10) business days at no additional cost.",
        "jurisdiction": "CA-Federal",
        "industry": "IT",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "Ontario",
        "clause_type": "Performance_Standards",
        "subtype": "SLA_IT_Services",
        "clause_text": "The Contractor shall maintain a minimum service availability of 99.5% measured on a monthly basis, excluding scheduled maintenance windows. The Contractor shall respond to critical incidents (Severity 1) within one (1) hour and resolve within four (4) hours. Service credits equal to 2% of monthly fees per 0.1% below the availability target shall be applied automatically.",
        "jurisdiction": "CA-ON",
        "industry": "IT",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "SACC",
        "clause_type": "Key_Personnel",
        "subtype": "Named_Resources",
        "clause_text": "The Contractor shall assign the key personnel identified in its proposal to perform the Work. The Contractor shall not remove or replace any key personnel without the prior written consent of the Technical Authority. Any proposed replacement must possess qualifications and experience equivalent to or greater than the individual being replaced.",
        "jurisdiction": "CA-Federal",
        "industry": "General",
        "risk_level": "Medium",
        "is_standard": True,
    },
    {
        "source": "Federal",
        "clause_type": "Reporting",
        "subtype": "Progress_Reports",
        "clause_text": "The Contractor shall submit written progress reports to the Technical Authority on a monthly basis, or as otherwise specified in the Statement of Work. Reports shall include: a summary of work completed during the reporting period, work planned for the next period, identification of risks and issues, and status against each milestone in Schedule A.",
        "jurisdiction": "CA-Federal",
        "industry": "General",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "SACC",
        "clause_type": "Quality_Assurance",
        "subtype": "QA_Program",
        "clause_text": "The Contractor shall implement and maintain a quality assurance program consistent with ISO 9001:2015 or equivalent. The Contractor shall submit its Quality Management Plan for approval within fifteen (15) business days of contract award. Canada reserves the right to conduct quality audits and inspections at any time during the Contract period.",
        "jurisdiction": "CA-Federal",
        "industry": "General",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "SACC",
        "clause_type": "Warranty",
        "subtype": "Standard_12_Month",
        "clause_text": "The Contractor warrants that all deliverables shall be free from defects in design, materials, and workmanship for a period of twelve (12) months from the date of written acceptance. During the warranty period, the Contractor shall, at no additional cost to Canada, repair or replace any defective deliverable within ten (10) business days of receiving notice.",
        "jurisdiction": "CA-Federal",
        "industry": "General",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "Ontario",
        "clause_type": "Warranty",
        "subtype": "Extended_24_Month",
        "clause_text": "The Contractor warrants that all deliverables, including software and documentation, shall conform to the specifications and be free from defects for a period of twenty-four (24) months from the date of final acceptance. The warranty shall include all patches, updates, and bug fixes necessary to maintain compliance with the specifications at no additional cost to Ontario.",
        "jurisdiction": "CA-ON",
        "industry": "IT",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "SACC",
        "clause_type": "Training",
        "subtype": "Knowledge_Transfer",
        "clause_text": "The Contractor shall provide comprehensive training to Canada's designated personnel on the use, operation, and maintenance of all deliverables. Training shall include hands-on sessions, user manuals, and administrator guides in both official languages. The Contractor shall deliver a minimum of three (3) training sessions of no less than eight (8) hours each.",
        "jurisdiction": "CA-Federal",
        "industry": "IT",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "Federal",
        "clause_type": "Transition_Services",
        "subtype": "Knowledge_Transfer",
        "clause_text": "Upon expiry or termination of this Contract, the Contractor shall provide transition services for a period of up to ninety (90) days to facilitate the orderly transfer of responsibilities to Canada or a successor contractor. Transition services shall include complete knowledge transfer, data migration, documentation of processes, and support for parallel operations.",
        "jurisdiction": "CA-Federal",
        "industry": "IT",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "Ontario",
        "clause_type": "Business_Continuity",
        "subtype": "BCP_DR",
        "clause_text": "The Contractor shall maintain a Business Continuity Plan (BCP) and Disaster Recovery Plan (DRP) that ensure recovery of critical services within four (4) hours (RTO) and data loss of no more than one (1) hour (RPO). The Contractor shall test its BCP/DRP at least annually and provide test results to the Technical Authority within thirty (30) days of each test.",
        "jurisdiction": "CA-ON",
        "industry": "IT",
        "risk_level": "Medium",
        "is_standard": True,
    },
    {
        "source": "SACC",
        "clause_type": "Project_Governance",
        "subtype": "Governance_Structure",
        "clause_text": "The Contractor shall participate in a joint project governance structure comprising a Steering Committee (meeting quarterly) and a Project Working Group (meeting bi-weekly). The Contractor's Project Manager shall serve as the primary point of contact and shall have authority to make decisions on behalf of the Contractor regarding day-to-day project matters.",
        "jurisdiction": "CA-Federal",
        "industry": "General",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "Ontario",
        "clause_type": "Change_Management",
        "subtype": "Change_Request_Process",
        "clause_text": "Any change to the scope of work set out in this Contract must be requested in writing and approved by both parties prior to implementation. The Contractor shall provide a written impact assessment, including any changes to cost, timeline, or deliverables, within five (5) business days of receiving a change request.",
        "jurisdiction": "CA-ON",
        "industry": "General",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "Federal",
        "clause_type": "Liquidated_Damages",
        "subtype": "Delay_Damages",
        "clause_text": "If the Contractor fails to deliver any deliverable by the date specified in Schedule A, Canada shall be entitled to liquidated damages equal to one percent (1%) of the value of the late deliverable for each week of delay, up to a maximum of ten percent (10%) of the total Contract Price. The parties agree that this amount represents a genuine pre-estimate of the damages Canada would suffer.",
        "jurisdiction": "CA-Federal",
        "industry": "General",
        "risk_level": "High",
        "is_standard": True,
    },
]
