"""Sector-specific clauses — IT/Cloud, Construction, Consulting."""

SECTOR_CLAUSES = [
    # ── IT / Cloud ───────────────────────────────────────────
    {
        "source": "Ontario",
        "clause_type": "Cloud_SaaS",
        "subtype": "SaaS_Terms",
        "clause_text": "The Contractor shall deliver the Software as a Service (SaaS) solution in accordance with the service levels set out in Schedule B. The Contractor shall provide a minimum of twelve (12) months' notice prior to end-of-life or discontinuation of the service. Upon termination, the Contractor shall provide data export in a standard format and maintain read-only access for a minimum of ninety (90) days.",
        "jurisdiction": "CA-ON",
        "industry": "IT",
        "risk_level": "Medium",
        "is_standard": True,
    },
    {
        "source": "Federal",
        "clause_type": "Agile_Development",
        "subtype": "Sprint_Delivery",
        "clause_text": "The Contractor shall deliver the Work using an Agile methodology with two-week sprint cycles. Each sprint shall produce potentially shippable increments of functionality as defined in the prioritized product backlog. Sprint planning, daily stand-ups, sprint reviews, and retrospectives shall include participation by Canada's Product Owner. Acceptance of each sprint deliverable shall be confirmed by the Product Owner within five (5) business days.",
        "jurisdiction": "CA-Federal",
        "industry": "IT",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "SACC",
        "clause_type": "Software_Maintenance",
        "subtype": "Support_Maintenance",
        "clause_text": "The Contractor shall provide software maintenance and support services for the duration of the Contract, including: (a) critical security patches within twenty-four (24) hours; (b) bug fixes within five (5) business days for Severity 1 and ten (10) business days for Severity 2; (c) quarterly minor releases incorporating approved enhancements; and (d) annual major releases with backward compatibility for a minimum of twelve (12) months.",
        "jurisdiction": "CA-Federal",
        "industry": "IT",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "Federal",
        "clause_type": "Data_Migration",
        "subtype": "Migration_Services",
        "clause_text": "The Contractor shall develop and execute a data migration plan to transfer all existing data from the legacy system to the new solution. The plan shall include data mapping, validation rules, cleansing procedures, and rollback strategy. The Contractor shall perform a minimum of two (2) trial migrations before the production migration and shall achieve a data migration accuracy rate of 99.9% or higher.",
        "jurisdiction": "CA-Federal",
        "industry": "IT",
        "risk_level": "Medium",
        "is_standard": True,
    },
    # ── Construction ─────────────────────────────────────────
    {
        "source": "SACC",
        "clause_type": "Substantial_Completion",
        "subtype": "Construction_Milestone",
        "clause_text": "Substantial Completion shall be achieved when the Work is ready for its intended use and complies with all codes and regulations, notwithstanding the existence of minor deficiencies that do not materially affect the use of the Work. The Contractor shall provide notice of Substantial Completion and Canada shall inspect within ten (10) business days. A deficiency list shall be prepared and the Contractor shall complete all deficiency work within thirty (30) days.",
        "jurisdiction": "CA-Federal",
        "industry": "Construction",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "Ontario",
        "clause_type": "Deficiency_List",
        "subtype": "Punch_List",
        "clause_text": "Upon notification of Substantial Completion, the Technical Authority shall prepare a comprehensive deficiency list identifying all items of Work that are incomplete, defective, or not in conformance with the Contract documents. The Contractor shall rectify all deficiency items within thirty (30) calendar days at no additional cost. Failure to complete deficiency work within this period may result in Canada engaging others to complete the work and deducting the cost from amounts owing.",
        "jurisdiction": "CA-ON",
        "industry": "Construction",
        "risk_level": "Medium",
        "is_standard": True,
    },
    {
        "source": "Ontario",
        "clause_type": "Site_Safety",
        "subtype": "Construction_Safety",
        "clause_text": "The Contractor is the constructor as defined in the Occupational Health and Safety Act, RSO 1990, c O.1, and shall be responsible for all health and safety matters at the work site. The Contractor shall appoint a competent supervisor, maintain a site-specific safety plan, conduct daily toolbox talks, and ensure all workers have completed mandatory health and safety training including Working at Heights where applicable.",
        "jurisdiction": "CA-ON",
        "industry": "Construction",
        "risk_level": "High",
        "is_standard": True,
    },
    {
        "source": "Ontario",
        "clause_type": "Builders_Lien",
        "subtype": "Lien_Protection",
        "clause_text": "The Contractor shall comply with the Construction Act, RSO 1990, c C.30, including all obligations respecting holdbacks, liens, and prompt payment. The Contractor shall ensure that all subcontractors and suppliers are paid in accordance with the prompt payment provisions and shall provide statutory declarations confirming payment prior to the release of any holdback.",
        "jurisdiction": "CA-ON",
        "industry": "Construction",
        "risk_level": "Medium",
        "is_standard": True,
    },
    # ── Consulting / Professional Services ───────────────────
    {
        "source": "SACC",
        "clause_type": "Professional_Standards",
        "subtype": "Standard_of_Care",
        "clause_text": "The Contractor shall perform the Work in accordance with the professional standards, practices, and codes of conduct applicable to the Contractor's profession and industry. The Contractor shall ensure that all personnel assigned to the Work hold the required professional designations, certifications, and memberships in good standing with the applicable regulatory body.",
        "jurisdiction": "CA-Federal",
        "industry": "Consulting",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "Federal",
        "clause_type": "Conflict_Disclosure",
        "subtype": "Consulting_COI",
        "clause_text": "The Contractor shall disclose to Canada, prior to commencing work and on an ongoing basis, any assignment, contract, or business relationship that could give rise to a real, potential, or apparent conflict of interest. The Contractor shall not provide advice to Canada on any matter in which the Contractor has a direct or indirect financial interest without full disclosure and written consent.",
        "jurisdiction": "CA-Federal",
        "industry": "Consulting",
        "risk_level": "Medium",
        "is_standard": True,
    },
    {
        "source": "SACC",
        "clause_type": "Deliverable_Ownership",
        "subtype": "Consulting_Outputs",
        "clause_text": "All reports, analyses, recommendations, presentations, data compilations, and other work product prepared by the Contractor in the course of this engagement shall be the exclusive property of Canada. The Contractor shall not publish, present, or otherwise disclose the findings or recommendations without the prior written consent of Canada.",
        "jurisdiction": "CA-Federal",
        "industry": "Consulting",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "Federal",
        "clause_type": "Staff_Augmentation",
        "subtype": "Resource_Engagement",
        "clause_text": "The Contractor shall provide qualified personnel to supplement Canada's project team as described in the Statement of Work. Personnel shall work under the day-to-day direction of Canada's Project Manager while remaining employees of the Contractor. The Contractor shall replace any resource within ten (10) business days if Canada determines, acting reasonably, that the resource does not meet the required competency level.",
        "jurisdiction": "CA-Federal",
        "industry": "Consulting",
        "risk_level": "Low",
        "is_standard": True,
    },
]
