"""Termination & Dispute Resolution clauses."""

TERMINATION_CLAUSES = [
    {
        "source": "Ontario",
        "clause_type": "Termination",
        "subtype": "Termination_Convenience",
        "clause_text": "Canada may, at any time, terminate this Contract for convenience by providing thirty (30) calendar days' written notice to the Contractor. Upon termination for convenience, Canada's liability is limited to payment for work satisfactorily performed and accepted prior to the termination date, together with reasonable and substantiated wind-down costs.",
        "jurisdiction": "CA-ON",
        "industry": "General",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "SACC",
        "clause_type": "Termination",
        "subtype": "Termination_Default",
        "clause_text": "Canada may terminate this Contract for default if the Contractor: (a) fails to perform any material obligation and does not cure within fifteen (15) business days after written notice; (b) becomes insolvent or makes an assignment for the benefit of creditors; or (c) is convicted of a criminal offence under the Integrity Provisions. Upon termination for default, Canada reserves all rights and remedies available at law and in equity.",
        "jurisdiction": "CA-Federal",
        "industry": "General",
        "risk_level": "Medium",
        "is_standard": True,
    },
    {
        "source": "Federal",
        "clause_type": "Termination",
        "subtype": "Termination_Insolvency",
        "clause_text": "Canada may immediately terminate this Contract, without notice or further obligation, if the Contractor: (a) becomes bankrupt or insolvent; (b) makes a proposal under the Bankruptcy and Insolvency Act, RSC 1985, c B-3; (c) has a receiver or receiver-manager appointed over its assets; or (d) is subject to proceedings under the Companies' Creditors Arrangement Act, RSC 1985, c C-36.",
        "jurisdiction": "CA-Federal",
        "industry": "General",
        "risk_level": "Medium",
        "is_standard": True,
    },
    {
        "source": "SACC",
        "clause_type": "Termination",
        "subtype": "Mutual_Termination",
        "clause_text": "This Contract may be terminated at any time by the mutual written agreement of both parties. The parties shall negotiate in good faith the terms of the termination, including payment for work completed, return of materials and data, and any transition obligations. A mutual termination agreement shall be set out in a formal amendment.",
        "jurisdiction": "CA-Federal",
        "industry": "General",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "SACC",
        "clause_type": "Suspension",
        "subtype": "Suspension_of_Work",
        "clause_text": "Canada may, at any time, by written notice, order the Contractor to suspend all or any part of the Work for a period of up to one hundred and eighty (180) days. During the suspension, the Contractor shall protect and preserve the Work already performed. If the suspension exceeds one hundred and eighty (180) days, the Contractor may request termination for convenience and Canada shall compensate the Contractor for demonstrated costs of the suspension.",
        "jurisdiction": "CA-Federal",
        "industry": "General",
        "risk_level": "Medium",
        "is_standard": True,
    },
    {
        "source": "SACC",
        "clause_type": "Dispute_Resolution",
        "subtype": "Escalation",
        "clause_text": "In the event of a dispute arising out of this Contract, the parties shall first attempt resolution through good-faith negotiation between the respective Project Managers for a period of ten (10) business days. If unresolved, the dispute shall be escalated to the respective senior executives for a further period of twenty (20) business days before either party may pursue formal dispute resolution.",
        "jurisdiction": "CA-Federal",
        "industry": "General",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "Ontario",
        "clause_type": "Dispute_Resolution",
        "subtype": "Mediation",
        "clause_text": "If a dispute is not resolved through escalation, either party may refer the matter to mediation administered by a mutually agreed mediator or, failing agreement, a mediator appointed by the ADR Institute of Ontario. The costs of mediation shall be shared equally. Mediation shall be conducted in accordance with the National Mediation Rules of the ADR Institute of Canada.",
        "jurisdiction": "CA-ON",
        "industry": "General",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "Ontario",
        "clause_type": "Dispute_Resolution",
        "subtype": "Arbitration",
        "clause_text": "If mediation fails, either party may refer the dispute to binding arbitration under the Arbitration Act, 1991, SO 1991, c 17. The arbitration shall be conducted by a single arbitrator in Toronto, Ontario, in the English language. The arbitrator's award shall be final and binding on the parties and may be entered as a judgment in any court of competent jurisdiction.",
        "jurisdiction": "CA-ON",
        "industry": "General",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "Federal",
        "clause_type": "Dispute_Resolution",
        "subtype": "Judicial_Review",
        "clause_text": "Nothing in this Contract shall be construed as limiting the right of either party to seek injunctive or equitable relief from a court of competent jurisdiction where irreparable harm would result from the breach. For federal Crown contracts, disputes may be referred to the Canadian International Trade Tribunal (CITT) for procurement-related complaints under the Canadian International Trade Tribunal Act, RSC 1985, c 47 (4th Supp).",
        "jurisdiction": "CA-Federal",
        "industry": "General",
        "risk_level": "Low",
        "is_standard": True,
    },
    {
        "source": "Federal",
        "clause_type": "Transition",
        "subtype": "Transition_on_Termination",
        "clause_text": "Upon expiry or termination of this Contract for any reason, the Contractor shall: (a) cooperate with Canada and any successor contractor for a transition period of up to ninety (90) days; (b) transfer all data, documentation, and work product to Canada; (c) provide knowledge transfer sessions; (d) continue to provide critical services as directed during the transition; and (e) return or destroy all confidential information of Canada.",
        "jurisdiction": "CA-Federal",
        "industry": "General",
        "risk_level": "Low",
        "is_standard": True,
    },
]
