"""
Advanced training data — Part 2: Clause-pairing and metadata extraction.
Vendor-friendly vs Customer-friendly variants + contract metadata anchors.
"""

CLAUSE_PAIR_TRAINING_DATA = [
    # ── Limitation of Liability ──────────────────────────────
    {
        "instruction": "Compare vendor-friendly and customer-friendly versions of a Limitation of Liability clause. Explain the differences and negotiation leverage.",
        "input": "Limitation of Liability clause for a $500K SaaS contract",
        "response": '{"vendor_friendly": "The Provider\'s aggregate liability shall not exceed the fees paid in the three (3) months preceding the claim. In no event shall the Provider be liable for indirect, incidental, consequential, or punitive damages, including loss of data, revenue, or profits.", "customer_friendly": "The Provider\'s aggregate liability shall not exceed two times (2x) the total annual fees paid or payable. The limitation on consequential damages shall not apply to: (a) data breaches; (b) IP indemnification; (c) fraud or wilful misconduct; (d) breaches of confidentiality. The Provider shall maintain cyber liability insurance of not less than $2,000,000.", "key_differences": ["Cap: 3 months fees vs 2x annual fees (8x difference)", "Consequential damages: blanket exclusion vs carved-out exceptions", "No insurance requirement vs $2M cyber liability mandate", "No data breach accountability vs explicit data breach carve-out"], "negotiation_tip": "Start with 2x annual fees and negotiate down. Never accept a cap below 1x annual fees. Always carve out data breaches and IP indemnification from the consequential damages exclusion."}'
    },
    # ── Indemnification ──────────────────────────────────────
    {
        "instruction": "Compare vendor-friendly and customer-friendly versions of an Indemnification clause.",
        "input": "Indemnification clause for an IT consulting engagement",
        "response": '{"vendor_friendly": "The Consultant shall indemnify the Client solely for direct damages arising from the Consultant\'s gross negligence or wilful misconduct in performing the Services. The Consultant\'s indemnification obligation shall not exceed the fees paid under this Agreement. The Client shall provide prompt notice and sole control of the defence.", "customer_friendly": "The Consultant shall defend, indemnify, and hold harmless the Client from all claims, damages, losses, and expenses (including reasonable legal fees) arising from: (a) any breach of this Agreement; (b) any negligent act or omission; (c) any IP infringement; (d) any breach of applicable law. The Consultant shall maintain professional liability insurance of $2,000,000 to support this obligation. The indemnification obligation shall survive termination for 3 years.", "key_differences": ["Trigger: gross negligence only vs any negligence or breach", "Scope: direct damages only vs all claims including legal fees", "Cap: fee-capped vs uncapped (backed by insurance)", "IP coverage: excluded vs explicitly included", "Survival: silent vs 3-year survival period"], "negotiation_tip": "Push for \'negligence\' not just \'gross negligence\' — the bar for gross negligence is very high in Canadian law. Always require insurance backing for the indemnity."}'
    },
    # ── Termination for Convenience ──────────────────────────
    {
        "instruction": "Compare vendor-friendly and customer-friendly versions of a Termination for Convenience clause.",
        "input": "Termination for Convenience in a 3-year managed services contract",
        "response": '{"vendor_friendly": "Either party may terminate this Agreement for convenience upon 180 days\' written notice. Upon termination by the Client for convenience, the Client shall pay: (a) all fees for services rendered; (b) a termination fee equal to 50% of the remaining contract value; (c) all demobilization and transition costs.", "customer_friendly": "The Client may terminate this Agreement for convenience upon 30 days\' written notice. Upon termination, the Client\'s liability is limited to payment for services satisfactorily performed and accepted prior to the termination date, together with reasonable and substantiated wind-down costs not exceeding 10% of the remaining contract value. No termination fee shall apply.", "key_differences": ["Notice period: 180 days vs 30 days", "Termination fee: 50% of remaining value vs no fee", "Wind-down costs: unlimited vs capped at 10%", "Mutuality: bilateral vs Client-only right"], "negotiation_tip": "In Crown procurement, termination for convenience is a standard Crown right with no termination fee — this is non-negotiable in SACC contracts. For commercial contracts, negotiate the termination fee down from 50% to 0-15% of remaining value."}'
    },
    # ── Data Residency ───────────────────────────────────────
    {
        "instruction": "Compare vendor-friendly and customer-friendly versions of a Data Residency clause for Canadian government contracts.",
        "input": "Data Residency clause for a cloud services contract with Protected B data",
        "response": '{"vendor_friendly": "The Provider shall use commercially reasonable efforts to store data within Canada. The Provider may process data outside Canada for disaster recovery, maintenance, or support purposes provided appropriate safeguards are in place. The Provider shall comply with applicable data protection laws.", "customer_friendly": "All data, including personal information, Protected B information, backups, logs, and metadata, shall be stored, processed, transmitted, and backed up exclusively within the geographic boundaries of Canada at all times. No data shall leave Canada for any purpose including disaster recovery, support, or maintenance without the prior written consent of Canada. The Provider shall certify the physical location of all data centres used and permit Canada to audit compliance. Any unauthorized transfer outside Canada shall constitute a material breach.", "key_differences": ["Scope: commercially reasonable efforts vs absolute requirement", "Exceptions: DR and support carve-outs vs no exceptions without consent", "Coverage: data only vs data, backups, logs, metadata", "Audit: no audit right vs certification and audit rights", "Breach: no consequence vs material breach for violation"], "negotiation_tip": "For Protected B data, there is no flexibility — data MUST stay in Canada per TBS Directive. Do not accept \'commercially reasonable efforts\' language. Require certification of data centre locations."}'
    },
    # ── Force Majeure ────────────────────────────────────────
    {
        "instruction": "Compare vendor-friendly and customer-friendly versions of a Force Majeure clause post-COVID.",
        "input": "Force Majeure clause for a supply chain contract",
        "response": '{"vendor_friendly": "Neither party shall be liable for delays caused by events beyond reasonable control, including but not limited to pandemic, epidemic, supply chain disruption, labour shortages, raw material shortages, transportation delays, government regulations, and any other cause that could not have been reasonably foreseen. The affected party shall be entitled to an equitable extension of time and price adjustment.", "customer_friendly": "Force Majeure events are limited to: acts of God, war, terrorism, fire, flood, earthquake, and government-ordered shutdowns. Pandemic and supply chain disruption are expressly excluded as foreseeable risks that the Supplier is expected to mitigate through business continuity planning. The Supplier shall maintain 90 days of safety stock. If a Force Majeure event continues for more than 60 days, the Purchaser may terminate without penalty.", "key_differences": ["Scope: expansive (including supply chain) vs narrow (acts of God only)", "Pandemic: included vs expressly excluded as foreseeable", "Price adjustment: automatic vs no adjustment", "Mitigation: no requirement vs 90-day safety stock mandate", "Termination: no right vs 60-day termination trigger"], "negotiation_tip": "Post-COVID, vendors will push to include pandemic and supply chain disruption. Resist this — these are now foreseeable risks. Instead, require business continuity plans and safety stock. Accept pandemic only if paired with a termination right after 60-90 days."}'
    },
]

METADATA_EXTRACTION_TRAINING_DATA = [
    {
        "instruction": "Extract key metadata fields from this procurement contract excerpt. Return JSON with entity_information, financials_scope, and legal_risk sections.",
        "input": "MASTER SERVICE AGREEMENT between Her Majesty the Queen in Right of Canada, represented by the Minister of Public Services and Procurement ('Canada') and Acme Technologies Inc., a corporation incorporated under the laws of Ontario ('the Contractor'). Effective Date: April 1, 2025. Expiration Date: March 31, 2028, with two (2) one-year renewal options. Total Contract Value: $4,200,000.00 CAD (including HST). Payment: Net 30 days upon receipt of approved invoice. SLA: 99.5% monthly availability with service credits of 2% per 0.1% below target. Limitation of Liability: Contractor's aggregate liability capped at 1x annual fees ($1,400,000). Indemnification: Contractor indemnifies Canada for IP infringement and data breaches without cap. Governing Law: Ontario and federal laws of Canada.",
        "response": '{"entity_information": {"parties": {"purchaser": "Her Majesty the Queen in Right of Canada (PSPC)", "supplier": "Acme Technologies Inc. (Ontario corporation)"}, "effective_date": "2025-04-01", "expiration_date": "2028-03-31", "renewal_options": "Two (2) one-year renewal options", "maximum_term": "5 years (3 + 2 renewals)"}, "financials_scope": {"total_contract_value": 4200000, "currency": "CAD", "includes_tax": true, "annual_value": 1400000, "payment_terms": "Net 30 days", "sla_target": "99.5% monthly availability", "sla_penalty": "2% of monthly fees per 0.1% below target", "max_monthly_credit": "Not specified — negotiate 30% cap"}, "legal_risk": {"limitation_of_liability": {"cap": "1x annual fees ($1,400,000)", "assessment": "Standard — acceptable for this contract value"}, "indemnification": {"scope": "IP infringement and data breaches", "cap": "Uncapped", "assessment": "Favorable to Canada — ensures full coverage for high-risk events"}, "governing_law": "Ontario + federal laws of Canada", "risk_level": "Medium — LoL cap is reasonable but verify carve-outs for fraud and gross negligence"}}'
    },
    {
        "instruction": "Extract key metadata fields from this RFP summary.",
        "input": "REQUEST FOR PROPOSAL: Enterprise Cloud Migration Services. Solicitation No.: EN578-220001. Closing Date: May 15, 2025, 14:00 ET. Contracting Authority: Public Services and Procurement Canada. Estimated Value: $15,000,000 - $20,000,000 CAD. Contract Period: 3 years with 2 one-year options. Security Requirement: Secret clearance. Evaluation: 70% Technical Merit / 30% Price. Minimum Technical Score: 70%. Basis of Payment: Firm fixed price for Phase 1, Time & Materials for Phase 2. Mandatory Requirements: ISO 27001 certification, GC Cloud Guardrails compliance, data residency in Canada, bilingual (EN/FR) deliverables.",
        "response": '{"entity_information": {"document_type": "Request for Proposal (RFP)", "solicitation_number": "EN578-220001", "contracting_authority": "Public Services and Procurement Canada", "closing_date": "2025-05-15T14:00:00-04:00"}, "financials_scope": {"estimated_value_low": 15000000, "estimated_value_high": 20000000, "currency": "CAD", "contract_period": "3 years + 2 one-year options (5 years max)", "basis_of_payment": "Fixed price (Phase 1) + Time & Materials (Phase 2)", "evaluation_method": "Highest combined rating — 70% Technical / 30% Price", "minimum_technical_score": "70%"}, "legal_risk": {"security_clearance": "Secret — allow 6+ months processing time", "mandatory_requirements": ["ISO 27001 certification", "GC Cloud Guardrails compliance", "Data residency in Canada", "Bilingual EN/FR deliverables"], "trade_agreements": "Likely subject to CFTA, CETA, and WTO GPA given value exceeds thresholds", "risk_assessment": "High complexity — fixed price Phase 1 creates cost overrun risk. Ensure scope is well-defined before bidding."}}'
    },
    {
        "instruction": "Extract key metadata from this Statement of Work excerpt.",
        "input": "STATEMENT OF WORK: Cybersecurity Assessment Services for Department of National Defence. Period of Performance: September 1, 2025 to August 31, 2026. Key Personnel: Lead Assessor (CISSP, 10+ years), Senior Penetration Tester (OSCP, 7+ years). Deliverables: Phase 1 — Vulnerability Assessment Report (due Oct 31); Phase 2 — Penetration Test Report (due Jan 31); Phase 3 — Remediation Roadmap (due Mar 31); Phase 4 — Executive Briefing (due May 31). All personnel require Top Secret clearance. Work location: On-site at DND facilities in Ottawa. Travel: No travel outside NCR anticipated. Acceptance: 15 business days review, 10 business day cure period.",
        "response": '{"entity_information": {"document_type": "Statement of Work (SOW)", "client": "Department of National Defence", "period_of_performance": {"start": "2025-09-01", "end": "2026-08-31", "duration": "12 months"}}, "financials_scope": {"key_personnel": [{"role": "Lead Assessor", "certifications": ["CISSP"], "experience": "10+ years"}, {"role": "Senior Penetration Tester", "certifications": ["OSCP"], "experience": "7+ years"}], "deliverables": [{"phase": 1, "name": "Vulnerability Assessment Report", "due_date": "2025-10-31"}, {"phase": 2, "name": "Penetration Test Report", "due_date": "2026-01-31"}, {"phase": 3, "name": "Remediation Roadmap", "due_date": "2026-03-31"}, {"phase": 4, "name": "Executive Briefing", "due_date": "2026-05-31"}], "acceptance_criteria": "15 business days review + 10 business day cure"}, "legal_risk": {"security_clearance": "Top Secret — very limited pool of candidates, allow 12+ months processing", "work_location": "On-site DND Ottawa — no remote work", "key_risk": "Top Secret clearance requirement severely limits available resources. Build clearance processing time into project schedule. Ensure key personnel are pre-cleared before bid submission."}}'
    },
]

PROCUREMENT_PROCESS_TRAINING_DATA = [
    {
        "instruction": "Explain the procurement process flow from RFQ to contract execution for a Canadian federal IT services procurement.",
        "input": "",
        "response": '{"process_steps": [{"step": 1, "name": "Requirements Definition", "description": "The client department defines the business need, prepares a Statement of Requirements, conducts market research, and determines the procurement strategy (competitive vs. sole-source). An Algorithmic Impact Assessment may be required for AI systems.", "key_documents": ["Statement of Requirements", "Procurement Plan", "Security Requirements Check List (SRCL)"]}, {"step": 2, "name": "RFQ/RFP Preparation", "description": "PSPC or the department prepares the solicitation document including: evaluation criteria (mandatory and rated), Statement of Work, Basis of Payment, security requirements, and all applicable SACC clauses. Trade agreement coverage is determined based on estimated value.", "key_documents": ["RFP/RFQ", "Statement of Work (SOW)", "Evaluation Criteria", "Draft Contract"]}, {"step": 3, "name": "Solicitation & Bid Period", "description": "The solicitation is published on CanadaBuys (buyandsell.gc.ca). Minimum bid period is 25 days for CFTA-covered procurements, 40 days for CETA/WTO GPA. An industry day or Q&A period may be held. All amendments are published.", "key_documents": ["Published RFP", "Amendment(s)", "Q&A Document"]}, {"step": 4, "name": "Bid Evaluation", "description": "Bids are evaluated in sequence: (1) Administrative compliance check; (2) Mandatory requirements pass/fail; (3) Rated technical criteria scored against published weights; (4) Financial evaluation of compliant bids. The evaluation is conducted by a team including technical evaluators and the contracting authority.", "key_documents": ["Evaluation Matrix", "Consensus Scoring Sheets", "Price Analysis"]}, {"step": 5, "name": "Contract Award", "description": "The contract is awarded to the highest-scoring compliant bidder. A regret letter is sent to unsuccessful bidders with an offer of debriefing. The award notice is published within 72 days. A 10-day standstill period applies for CETA-covered procurements.", "key_documents": ["Award Letter", "Regret Letters", "Contract", "Award Notice"]}, {"step": 6, "name": "Contract Execution & Management", "description": "The contract is executed by both parties. A kick-off meeting is held. The Project Authority manages day-to-day performance. The Contracting Authority manages contract amendments, payments, and compliance. Performance is monitored against SLAs and deliverable milestones.", "key_documents": ["Signed Contract", "Project Charter", "Progress Reports", "Invoices"]}]}'
    },
]
