"""
Advanced training data — Part 1: Scenario-based reasoning chains.
Procurement disputes, drafting exercises, and negotiation logic.
"""

SCENARIO_TRAINING_DATA = [
    # ── Software License Dispute ─────────────────────────────
    {
        "instruction": "Generate a complex procurement scenario involving a Software License dispute. A vendor has updated their Acceptable Use Policy mid-contract. Draft a 3-step reasoning chain: Issue Identification, Contractual Remedy, Drafted Response.",
        "context": "The Purchaser entered into a 3-year Master Service Agreement with a SaaS vendor. Section 12.3 of the MSA states: 'No amendment to this Agreement shall be valid unless set out in a formal written amendment executed by both parties.' The vendor unilaterally updated their Acceptable Use Policy to prohibit a use case that is core to the Purchaser's operations.",
        "response": '{"issue_identification": "The vendor has breached Section 12.3 (Amendments) by unilaterally modifying the Acceptable Use Policy, which is incorporated by reference into the MSA. Under Canadian contract law, a unilateral change to material terms without consent constitutes a breach of contract. The change also potentially triggers the Material Adverse Change clause if it substantially impairs the Purchaser\'s intended use.", "contractual_remedy": "Section 12.3 requires mutual written consent for amendments. Section 18.1 (Termination for Default) permits the Purchaser to terminate if the vendor fails to cure a material breach within 15 business days of written notice. Section 14.2 (Dispute Resolution) requires escalation to senior management before formal proceedings. The Purchaser may also seek injunctive relief to prevent enforcement of the unilateral change.", "drafted_response": "NOTICE OF DISPUTE\\n\\nTo: [Vendor Legal Department]\\nFrom: [Purchaser]\\nDate: [Date]\\nRe: Unauthorized Amendment to Acceptable Use Policy — MSA Reference No. [XXX]\\n\\nWe write to formally notify you that your unilateral update to the Acceptable Use Policy dated [Date] constitutes a material breach of Section 12.3 of the Master Service Agreement executed between our organizations on [Date].\\n\\nSection 12.3 expressly requires that amendments be set out in a formal written amendment executed by both parties. No such amendment was negotiated, agreed to, or executed.\\n\\nWe hereby demand that you: (1) immediately revert the Acceptable Use Policy to the version in effect at the date of the MSA; (2) confirm in writing within 15 business days that the prior version is reinstated; and (3) refrain from making further unilateral changes to any incorporated documents.\\n\\nFailure to cure this breach within 15 business days may result in termination of the MSA pursuant to Section 18.1 and pursuit of all available remedies at law and in equity.\\n\\nYours truly,\\n[Purchaser Representative]"}'
    },
    # ── Construction Delay Claim ──────────────────────────────
    {
        "instruction": "Analyze a construction procurement dispute where the contractor claims Force Majeure due to supply chain disruption. Identify the relevant clauses, assess the claim, and draft a response.",
        "context": "A federal construction contract for a $42M office renovation includes a Force Majeure clause (Section 9.1) that covers 'acts of God, war, terrorism, fire, flood, epidemic, pandemic, and governmental action.' The contractor claims a 6-month delay due to global steel supply shortages. The contract also includes a Liquidated Damages clause at 1% per week of delay, capped at 10%.",
        "response": '{"issue_identification": "The contractor is claiming Force Majeure under Section 9.1 for supply chain disruption. However, general supply shortages and price increases are typically NOT Force Majeure events unless the clause specifically includes \'supply chain disruption\' or \'shortage of materials.\' The listed events (acts of God, war, etc.) are narrower. The contractor bears the burden of proving the event was beyond reasonable control and that mitigation efforts were undertaken.", "contractual_remedy": "Section 9.1 requires: (a) prompt written notice (within 5 business days); (b) evidence the delay was caused by a Force Majeure event; (c) demonstration of mitigation efforts. If the claim fails, Section 15.2 (Liquidated Damages) applies at 1% per week. For a 26-week delay on $42M, that is $4.2M capped at $4.2M (10% of $42M). The Purchaser should request: timeline of notice, evidence of steel sourcing attempts, and alternative supplier analysis.", "drafted_response": "RE: Force Majeure Claim — Contract No. [XXX]\\n\\nWe acknowledge receipt of your Force Majeure claim dated [Date]. After review, we note the following concerns:\\n\\n1. Section 9.1 does not specifically enumerate supply chain disruption or material shortages as Force Majeure events.\\n2. Your notice was provided [X] days after the alleged triggering event, exceeding the 5-business-day notice requirement.\\n3. No evidence of mitigation efforts (alternative suppliers, material substitution) has been provided.\\n\\nPlease provide within 10 business days: (a) documentary evidence that steel was unavailable from all reasonable sources; (b) a log of alternative suppliers contacted; (c) a revised project schedule showing the critical path impact.\\n\\nPending review of this evidence, we reserve all rights under Section 15.2 (Liquidated Damages)."}'
    },
    # ── Data Breach Indemnification ───────────────────────────
    {
        "instruction": "A SaaS vendor suffered a data breach affecting the Purchaser's customer data. Analyze the indemnification and data breach notification obligations.",
        "context": "The MSA includes: Section 8.1 (Data Breach Notification) requiring 24-hour notice. Section 11.3 (Indemnification) states the vendor shall indemnify the Purchaser for losses arising from vendor's breach of data protection obligations. Section 13.1 (Limitation of Liability) caps aggregate liability at 12 months' fees ($240,000). Section 8.4 requires the vendor to bear costs of breach response including notification and credit monitoring. The vendor notified the Purchaser 72 hours after discovering the breach.",
        "response": '{"issue_identification": "Two breaches: (1) Late notification — Section 8.1 requires 24-hour notice but vendor took 72 hours, a 48-hour delay. (2) The underlying data breach itself triggers indemnification under Section 11.3. Under PIPEDA and Ontario PHIPA, the Purchaser may have independent notification obligations to affected individuals. The late vendor notice has shortened the Purchaser\'s response window.", "contractual_remedy": "Section 11.3 indemnification covers: breach response costs, notification to affected individuals, credit monitoring, forensic investigation, and regulatory fines. Section 8.4 explicitly allocates these costs to the vendor. However, Section 13.1 caps aggregate liability at $240,000 (12 months\' fees). Key question: does the liability cap carve out data breach indemnification? If Section 13.4 (Carve-Outs) excludes data protection breaches from the cap, full recovery is available. If not, recovery is limited to $240,000.", "drafted_response": "NOTICE OF INDEMNIFICATION CLAIM\\n\\nWe hereby provide formal notice of an indemnification claim under Section 11.3 of the MSA.\\n\\nThe data breach disclosed on [Date] has resulted in the following losses to date:\\n- Forensic investigation costs: $85,000\\n- Legal counsel fees: $45,000\\n- Customer notification costs (estimated): $120,000\\n- Credit monitoring services (estimated): $200,000\\n- Regulatory response costs: $30,000\\n\\nWe note that your notification was provided 72 hours after discovery, in violation of the 24-hour requirement in Section 8.1. This delay has materially impacted our ability to mitigate harm.\\n\\nPlease confirm within 5 business days that you accept the indemnification obligation and provide your insurer\'s contact information for direct claims coordination."}'
    },
    # ── Procurement Bid Challenge (CITT) ─────────────────────
    {
        "instruction": "A losing bidder believes the procurement evaluation was unfair. Analyze whether they have grounds for a CITT complaint and draft the complaint framework.",
        "context": "A federal IT services procurement used 70% technical / 30% price evaluation. The losing bidder scored 72% technical (above the 70% threshold) but was ranked second. The winning bidder's technical score was 68% but their price was 40% lower. The RFP stated the minimum technical score was 70%. The losing bidder believes the winning bidder should have been disqualified for failing to meet the minimum technical threshold.",
        "response": '{"issue_identification": "If the winning bidder scored 68% technical against a stated minimum threshold of 70%, they should have been screened out before price evaluation. Awarding to a bidder that failed mandatory requirements violates CFTA Article 504 (non-discrimination and transparency) and the evaluation methodology published in the RFP. This is a strong ground for a CITT complaint.", "contractual_remedy": "Under the CITT Procurement Inquiry Regulations (SOR/93-602), the complainant must file within 10 working days of learning the basis for the complaint. The CITT can recommend: (a) re-evaluation excluding the non-compliant bid; (b) contract termination and re-tender; or (c) compensation for bid preparation costs or lost profits. Given that the complainant met all mandatory requirements and the winner did not, re-evaluation is the most likely remedy.", "drafted_response": "COMPLAINT TO THE CANADIAN INTERNATIONAL TRADE TRIBUNAL\\n\\nComplainant: [Company Name]\\nProcurement Reference: [Solicitation No.]\\nContracting Department: [Department]\\n\\nGROUNDS FOR COMPLAINT:\\n\\n1. The RFP (Section 4.2) established a mandatory minimum technical score of 70%.\\n2. The successful bidder received a technical score of 68%, below the mandatory threshold.\\n3. Despite failing to meet mandatory requirements, the successful bidder was not disqualified and was awarded the contract.\\n4. This evaluation is inconsistent with the published evaluation criteria and violates CFTA Article 504.\\n\\nRELIEF SOUGHT:\\n(a) A determination that the procurement was not conducted in accordance with CFTA Chapter 5;\\n(b) Re-evaluation of bids with the non-compliant bid excluded;\\n(c) Award of the contract to the Complainant; or\\n(d) In the alternative, compensation for bid preparation costs of $[Amount] and lost profits of $[Amount].\\n\\nThis complaint is filed within 10 working days of the Complainant becoming aware of the evaluation results."}'
    },
    # ── SLA Penalty Dispute ──────────────────────────────────
    {
        "instruction": "A cloud service provider failed to meet the 99.5% uptime SLA for three consecutive months. Analyze the contractual remedies and draft a notice.",
        "context": "The MSA specifies 99.5% monthly availability. Actual uptime was: Month 1: 98.2%, Month 2: 97.8%, Month 3: 99.1%. Service credits are 2% of monthly fees per 0.1% below target. Monthly fee is $50,000. Section 18.3 allows termination if SLA is missed for three consecutive months.",
        "response": '{"issue_identification": "The vendor has failed the 99.5% uptime SLA for three consecutive months. Service credit calculations: Month 1: (99.5-98.2)/0.1 x 2% = 26% of $50,000 = $13,000. Month 2: (99.5-97.8)/0.1 x 2% = 34% of $50,000 = $17,000 (likely capped at 30% = $15,000). Month 3: (99.5-99.1)/0.1 x 2% = 8% of $50,000 = $4,000. Total credits: $32,000. Additionally, Section 18.3 termination right is now triggered.", "contractual_remedy": "The Purchaser has two options: (1) Claim service credits of $32,000 and require a remediation plan with binding improvement targets; (2) Exercise the termination right under Section 18.3 due to three consecutive months of SLA failure. If terminating, the Purchaser is entitled to transition services (Section 20.1) for up to 90 days and must invoke data portability rights.", "drafted_response": "NOTICE OF SLA BREACH AND TERMINATION RIGHT\\n\\nThis letter serves as formal notice that your service has failed to meet the 99.5% availability SLA for three consecutive months:\\n- [Month 1]: 98.2% (1.3% below SLA)\\n- [Month 2]: 97.8% (1.7% below SLA)\\n- [Month 3]: 99.1% (0.4% below SLA)\\n\\nService credits totalling $32,000 are due immediately.\\n\\nPursuant to Section 18.3, we hereby reserve our right to terminate this Agreement. Before exercising this right, we require within 10 business days: (1) root cause analysis for each outage; (2) a binding remediation plan with monthly improvement targets; (3) confirmation of service credits.\\n\\nFailure to provide a satisfactory remediation plan will result in termination with 30 days notice."}'
    },
    # ── IP Ownership Dispute in Agile Project ────────────────
    {
        "instruction": "An IT contractor claims ownership of software code developed under a federal agile development contract. Analyze the IP provisions and draft a Crown assertion of ownership.",
        "context": "A federal agile development contract (Section 7.1) states all Foreground IP vests in Canada upon creation. The contractor embedded a proprietary framework (Background IP) into the deliverables without disclosure. Section 7.3 requires the contractor to disclose all Background IP in Schedule D. Schedule D was left blank. The contractor now claims the entire codebase is their IP because it is built on their proprietary framework.",
        "response": '{"issue_identification": "Two issues: (1) Section 7.1 clearly vests all Foreground IP in Canada. Code written during the contract is Foreground IP regardless of what framework it uses. (2) The contractor breached Section 7.3 by failing to disclose the proprietary framework in Schedule D. By incorporating undisclosed Background IP, the contractor has created an entanglement that does not change Canada\'s ownership of Foreground IP but may complicate extraction.", "contractual_remedy": "Canada owns the Foreground IP under Section 7.1. The contractor\'s failure to disclose Background IP in Schedule D is a material breach. Under Section 7.4, where Background IP is incorporated into deliverables, the contractor grants Canada a non-exclusive, irrevocable, royalty-free licence. Canada should: (a) assert Foreground IP ownership; (b) demand the Background IP licence under Section 7.4; (c) require the contractor to provide documentation enabling Canada to use the deliverables independently; (d) consider requiring the contractor to refactor to remove proprietary dependencies.", "drafted_response": "RE: Assertion of Crown Intellectual Property Rights — Contract No. [XXX]\\n\\nCanada hereby asserts its ownership of all Foreground Intellectual Property created under this Contract pursuant to Section 7.1.\\n\\nWe note that your proprietary framework was incorporated into the deliverables without disclosure in Schedule D, in breach of Section 7.3. This non-disclosure does not alter Canada\'s IP rights. Pursuant to Section 7.4, you have granted Canada a non-exclusive, irrevocable, royalty-free licence to all Background IP incorporated into the deliverables.\\n\\nYou are directed to: (1) provide complete source code, build scripts, and documentation within 10 business days; (2) identify all Background IP components in writing; (3) confirm the licence grant under Section 7.4; (4) provide a refactoring plan to reduce proprietary dependencies.\\n\\nFailure to comply may result in termination for default under Section 18.1."}'
    },
]
