"""
Advanced training data — Part 2: Clause-pairing and metadata extraction.
Vendor-friendly vs Customer-friendly variants + contract metadata anchors.
"""

CLAUSE_PAIR_TRAINING_DATA = [
    # ── Limitation of Liability ──────────────────────────────
    {
        "instruction": "Compare vendor-friendly and customer-friendly versions of a Limitation of Liability clause. Explain the differences and negotiation leverage.",
        "input": "Limitation of Liability clause for a $500K SaaS contract",
        "response": '{"vendor_friendly": "The Provider\'s aggregate liability shall not exceed the fees paid in the three (3) months preceding the claim. In no event shall the Provider be liable for indirect, incidental, consequential, or punitive damages, including loss of data, revenue, or profits.", "customer_friendly": "The Provider\'s aggregate liability shall not exceed two times (2x) the total annual fees paid or payable. The limitation on consequential damages shall not apply to: (a) data breaches; (b) IP indemnification; (c) fraud or wilful misconduct; (d) breaches of confidentiality. The Provider shall maintain cyber liability insurance of not less than $2,000,000.", "key_differences": ["Cap: 3 months fees vs 2x annual fees (8x difference)", "Consequential damages: blanket exclusion vs carved-out exceptions", "No insurance requirement vs $2M cyber liability mandate", "No data breach accountability vs explicit data breach carve-out"], "negotiation_tip": "Start with 2x annual fees and negotiate down. Never accept a cap below 1x annual fees. Always carve out data breaches and IP indemnification from the consequential damages exclusion."}'
    },
    # ── Indemnification ──────────────────────────────────────
    {
        "instruction": "Compare vendor-friendly and customer-friendly versions of an Indemnification clause.",
        "input": "Indemnification clause for an IT consulting engagement",
        "response": '{"vendor_friendly": "The Consultant shall indemnify the Client solely for direct damages arising from the Consultant\'s gross negligence or wilful misconduct in performing the Services. The Consultant\'s indemnification obligation shall not exceed the fees paid under this Agreement. The Client shall provide prompt notice and sole control of the defence.", "customer_friendly": "The Consultant shall defend, indemnify, and hold harmless the Client from all claims, damages, losses, and expenses (including reasonable legal fees) arising from: (a) any breach of this Agreement; (b) any negligent act or omission; (c) any IP infringement; (d) any breach of applicable law. The Consultant shall maintain professional liability insurance of $2,000,000 to support this obligation. The indemnification obligation shall survive termination for 3 years.", "key_differences": ["Trigger: gross negligence only vs any negligence or breach", "Scope: direct damages only vs all claims including legal fees", "Cap: fee-capped vs uncapped (backed by insurance)", "IP coverage: excluded vs explicitly included", "Survival: silent vs 3-year survival period"], "negotiation_tip": "Push for \'negligence\' not just \'gross negligence\' — the bar for gross negligence is very high in Canadian law. Always require insurance backing for the indemnity."}'
    },
    # ── Termination for Convenience ──────────────────────────
    {
        "instruction": "Compare vendor-friendly and customer-friendly versions of a Termination for Convenience clause.",
        "input": "Termination for Convenience in a 3-year managed services contract",
        "response": '{"vendor_friendly": "Either party may terminate this Agreement for convenience upon 180 days\' written notice. Upon termination by the Client for convenience, the Client shall pay: (a) all fees for services rendered; (b) a termination fee equal to 50% of the remaining contract value; (c) all demobilization and transition costs.", "customer_friendly": "The Client may terminate this Agreement for convenience upon 30 days\' written notice. Upon termination, the Client\'s liability is limited to payment for services satisfactorily performed and accepted prior to the termination date, together with reasonable and substantiated wind-down costs not exceeding 10% of the remaining contract value. No termination fee shall apply.", "key_differences": ["Notice period: 180 days vs 30 days", "Termination fee: 50% of remaining value vs no fee", "Wind-down costs: unlimited vs capped at 10%", "Mutuality: bilateral vs Client-only right"], "negotiation_tip": "In Crown procurement, termination for convenience is a standard Crown right with no termination fee — this is non-negotiable in SACC contracts. For commercial contracts, negotiate the termination fee down from 50% to 0-15% of remaining value."}'
    },
    # ── Data Residency ───────────────────────────────────────
    {
        "instruction": "Compare vendor-friendly and customer-friendly versions of a Data Residency clause for Canadian government contracts.",
        "input": "Data Residency clause for a cloud services contract with Protected B data",
        "response": '{"vendor_friendly": "The Provider shall use commercially reasonable efforts to store data within Canada. The Provider may process data outside Canada for disaster recovery, maintenance, or support purposes provided appropriate safeguards are in place. The Provider shall comply with applicable data protection laws.", "customer_friendly": "All data, including personal information, Protected B information, backups, logs, and metadata, shall be stored, processed, transmitted, and backed up exclusively within the geographic boundaries of Canada at all times. No data shall leave Canada for any purpose including disaster recovery, support, or maintenance without the prior written consent of Canada. The Provider shall certify the physical location of all data centres used and permit Canada to audit compliance. Any unauthorized transfer outside Canada shall constitute a material breach.", "key_differences": ["Scope: commercially reasonable efforts vs absolute requirement", "Exceptions: DR and support carve-outs vs no exceptions without consent", "Coverage: data only vs data, backups, logs, metadata", "Audit: no audit right vs certification and audit rights", "Breach: no consequence vs material breach for violation"], "negotiation_tip": "For Protected B data, there is no flexibility — data MUST stay in Canada per TBS Directive. Do not accept \'commercially reasonable efforts\' language. Require certification of data centre locations."}'
    },
    # ── Force Majeure ────────────────────────────────────────
    {
        "instruction": "Compare vendor-friendly and customer-friendly versions of a Force Majeure clause post-COVID.",
        "input": "Force Majeure clause for a supply chain contract",
        "response": '{"vendor_friendly": "Neither party shall be liable for delays caused by events beyond reasonable control, including but not limited to pandemic, epidemic, supply chain disruption, labour shortages, raw material shortages, transportation delays, government regulations, and any other cause that could not have been reasonably foreseen. The affected party shall be entitled to an equitable extension of time and price adjustment.", "customer_friendly": "Force Majeure events are limited to: acts of God, war, terrorism, fire, flood, earthquake, and government-ordered shutdowns. Pandemic and supply chain disruption are expressly excluded as foreseeable risks that the Supplier is expected to mitigate through business continuity planning. The Supplier shall maintain 90 days of safety stock. If a Force Majeure event continues for more than 60 days, the Purchaser may terminate without penalty.", "key_differences": ["Scope: expansive (including supply chain) vs narrow (acts of God only)", "Pandemic: included vs expressly excluded as foreseeable", "Price adjustment: automatic vs no adjustment", "Mitigation: no requirement vs 90-day safety stock mandate", "Termination: no right vs 60-day termination trigger"], "negotiation_tip": "Post-COVID, vendors will push to include pandemic and supply chain disruption. Resist this — these are now foreseeable risks. Instead, require business continuity plans and safety stock. Accept pandemic only if paired with a termination right after 60-90 days."}'
    },
]

METADATA_EXTRACTION_TRAINING_DATA = [
    {
        "instruction": "Extract key metadata fields from this procurement contract excerpt. Return JSON with entity_information, financials_scope, and legal_risk sections.",
        "input": "MASTER SERVICE AGREEMENT between Her Majesty the Queen in Right of Canada, represented by the Minister of Public Services and Procurement ('Canada') and Acme Technologies Inc., a corporation incorporated under the laws of Ontario ('the Contractor'). Effective Date: April 1, 2025. Expiration Date: March 31, 2028, with two (2) one-year renewal options. Total Contract Value: $4,200,000.00 CAD (including HST). Payment: Net 30 days upon receipt of approved invoice. SLA: 99.5% monthly availability with service credits of 2% per 0.1% below target. Limitation of Liability: Contractor's aggregate liability capped at 1x annual fees ($1,400,000). Indemnification: Contractor indemnifies Canada for IP infringement and data breaches without cap. Governing Law: Ontario and federal laws of Canada.",
        "response": '{"entity_information": {"parties": {"purchaser": "Her Majesty the Queen in Right of Canada (PSPC)", "supplier": "Acme Technologies Inc. (Ontario corporation)"}, "effective_date": "2025-04-01", "expiration_date": "2028-03-31", "renewal_options": "Two (2) one-year renewal options", "maximum_term": "5 years (3 + 2 renewals)"}, "financials_scope": {"total_contract_value": 4200000, "currency": "CAD", "includes_tax": true, "annual_value": 1400000, "payment_terms": "Net 30 days", "sla_target": "99.5% monthly availability", "sla_penalty": "2% of monthly fees per 0.1% below target", "max_monthly_credit": "Not specified — negotiate 30% cap"}, "legal_risk": {"limitation_of_liability": {"cap": "1x annual fees ($1,400,000)", "assessment": "Standard — acceptable for this contract value"}, "indemnification": {"scope": "IP infringement and data breaches", "cap": "Uncapped", "assessment": "Favorable to Canada — ensures full coverage for high-risk events"}, "governing_law": "Ontario + federal laws of Canada", "risk_level": "Medium — LoL cap is reasonable but verify carve-outs for fraud and gross negligence"}}'
    },
    {
        "instruction": "Extract key metadata fields from this RFP summary.",
        "input": "REQUEST FOR PROPOSAL: Enterprise Cloud Migration Services. Solicitation No.: EN578-220001. Closing Date: May 15, 2025, 14:00 ET. Contracting Authority: Public Services and Procurement Canada. Estimated Value: $15,000,000 - $20,000,000 CAD. Contract Period: 3 years with 2 one-year options. Security Requirement: Secret clearance. Evaluation: 70% Technical Merit / 30% Price. Minimum Technical Score: 70%. Basis of Payment: Firm fixed price for Phase 1, Time & Materials for Phase 2. Mandatory Requirements: ISO 27001 certification, GC Cloud Guardrails compliance, data residency in Canada, bilingual (EN/FR) deliverables.",
        "response": '{"entity_information": {"document_type": "Request for Proposal (RFP)", "solicitation_number": "EN578-220001", "contracting_authority": "Public Services and Procurement Canada", "closing_date": "2025-05-15T14:00:00-04:00"}, "financials_scope": {"estimated_value_low": 15000000, "estimated_value_high": 20000000, "currency": "CAD", "contract_period": "3 years + 2 one-year options (5 years max)", "basis_of_payment": "Fixed price (Phase 1) + Time & Materials (Phase 2)", "evaluation_method": "Highest combined rating — 70% Technical / 30% Price", "minimum_technical_score": "70%"}, "legal_risk": {"security_clearance": "Secret — allow 6+ months processing time", "mandatory_requirements": ["ISO 27001 certification", "GC Cloud Guardrails compliance", "Data residency in Canada", "Bilingual EN/FR deliverables"], "trade_agreements": "Likely subject to CFTA, CETA, and WTO GPA given value exceeds thresholds", "risk_assessment": "High complexity — fixed price Phase 1 creates cost overrun risk. Ensure scope is well-defined before bidding."}}'
    },
    {
        "instruction": "Extract key metadata from this Statement of Work excerpt.",
        "input": "STATEMENT OF WORK: Cybersecurity Assessment Services for Department of National Defence. Period of Performance: September 1, 2025 to August 31, 2026. Key Personnel: Lead Assessor (CISSP, 10+ years), Senior Penetration Tester (OSCP, 7+ years). Deliverables: Phase 1 — Vulnerability Assessment Report (due Oct 31); Phase 2 — Penetration Test Report (due Jan 31); Phase 3 — Remediation Roadmap (due Mar 31); Phase 4 — Executive Briefing (due May 31). All personnel require Top Secret clearance. Work location: On-site at DND facilities in Ottawa. Travel: No travel outside NCR anticipated. Acceptance: 15 business days review, 10 business day cure period.",
        "response": '{"entity_information": {"document_type": "Statement of Work (SOW)", "client": "Department of National Defence", "period_of_performance": {"start": "2025-09-01", "end": "2026-08-31", "duration": "12 months"}}, "financials_scope": {"key_personnel": [{"role": "Lead Assessor", "certifications": ["CISSP"], "experience": "10+ years"}, {"role": "Senior Penetration Tester", "certifications": ["OSCP"], "experience": "7+ years"}], "deliverables": [{"phase": 1, "name": "Vulnerability Assessment Report", "due_date": "2025-10-31"}, {"phase": 2, "name": "Penetration Test Report", "due_date": "2026-01-31"}, {"phase": 3, "name": "Remediation Roadmap", "due_date": "2026-03-31"}, {"phase": 4, "name": "Executive Briefing", "due_date": "2026-05-31"}], "acceptance_criteria": "15 business days review + 10 business day cure"}, "legal_risk": {"security_clearance": "Top Secret — very limited pool of candidates, allow 12+ months processing", "work_location": "On-site DND Ottawa — no remote work", "key_risk": "Top Secret clearance requirement severely limits available resources. Build clearance processing time into project schedule. Ensure key personnel are pre-cleared before bid submission."}}'
    },
]

METADATA_EXTRACTION_TRAINING_DATA_EXTRA = [
    {
        "instruction": "Extract key metadata fields from this construction contract excerpt. Return JSON with entity_information, financials_scope, and legal_risk.",
        "input": "CONSTRUCTION CONTRACT between Ontario Infrastructure Corp ('Owner') and BuildRight Construction Ltd ('Contractor'). Project: Highway 401 Bridge Rehabilitation. Effective Date: June 1, 2025. Substantial Completion: November 30, 2026. Contract Price: $28,500,000 CAD (firm fixed price). Payment: Monthly progress claims less 10% statutory holdback per Construction Act, RSO 1990, c C.30. Liquidated Damages: $15,000 per calendar day of delay. Performance Bond: 50% of contract price. Labour & Material Bond: 50% of contract price. Insurance: CGL $10,000,000 per occurrence. Professional Liability: $5,000,000. Builder's Risk: Full replacement value. Governing Law: Ontario.",
        "response": '{"entity_information": {"parties": {"purchaser": "Ontario Infrastructure Corp (Owner)", "supplier": "BuildRight Construction Ltd (Contractor)"}, "effective_date": "2025-06-01", "substantial_completion": "2026-11-30", "duration": "18 months"}, "financials_scope": {"contract_price": 28500000, "currency": "CAD", "pricing_model": "Firm fixed price", "payment_terms": "Monthly progress claims less 10% statutory holdback", "holdback_percentage": 10, "holdback_legislation": "Construction Act, RSO 1990, c C.30", "liquidated_damages": "$15,000 per calendar day of delay"}, "legal_risk": {"performance_bond": "50% of contract price ($14,250,000)", "labour_material_bond": "50% of contract price ($14,250,000)", "insurance": {"cgl": "$10,000,000 per occurrence", "professional_liability": "$5,000,000", "builders_risk": "Full replacement value"}, "governing_law": "Ontario", "risk_assessment": "High value construction — liquidated damages of $15K/day is aggressive. For a 30-day delay, exposure is $450,000. Ensure schedule has adequate float. Verify bond capacity with surety."}}'
    },
    {
        "instruction": "Extract key metadata fields from this IT outsourcing agreement. Return JSON with entity_information, financials_scope, and legal_risk.",
        "input": "IT MANAGED SERVICES AGREEMENT between Bank of Canada ('Client') and SecureOps IT Inc. ('Provider'). Term: 5 years commencing January 1, 2025 with two 2-year renewal options. Annual Fee: $3,600,000 CAD payable monthly ($300,000/month). Price Escalation: Annual CPI adjustment capped at 3%. SLA: 99.99% availability for Tier 1 systems, 99.9% for Tier 2. Service Credits: 5% of monthly fee per 0.01% below target, capped at 30% monthly. Key Personnel: Named CISO, SOC Manager, 4 Senior Analysts. Security: Top Secret clearance for all personnel. Data: All data Protected B, must remain in Canada. Limitation of Liability: 2x annual fees ($7,200,000). Indemnification: Uncapped for data breaches and security incidents. Termination for Convenience: 90 days notice, no termination fee. Governing Law: Federal laws of Canada.",
        "response": '{"entity_information": {"parties": {"purchaser": "Bank of Canada (Client)", "supplier": "SecureOps IT Inc. (Provider)"}, "effective_date": "2025-01-01", "initial_term": "5 years", "renewal_options": "Two 2-year renewal options", "maximum_term": "9 years"}, "financials_scope": {"annual_fee": 3600000, "monthly_fee": 300000, "currency": "CAD", "total_initial_term_value": 18000000, "total_maximum_value": 32400000, "price_escalation": "Annual CPI, capped at 3%", "payment_terms": "Monthly", "sla": {"tier_1": "99.99% availability", "tier_2": "99.9% availability"}, "service_credits": "5% per 0.01% below target, 30% monthly cap", "key_personnel": ["CISO", "SOC Manager", "4 Senior Analysts"]}, "legal_risk": {"limitation_of_liability": {"cap": "2x annual fees ($7,200,000)", "assessment": "Strong — 2x annual is above market average of 1x"}, "indemnification": {"scope": "Uncapped for data breaches and security incidents", "assessment": "Favorable to Client — appropriate given Protected B data"}, "data_classification": "Protected B", "data_residency": "Canada only", "security_clearance": "Top Secret for all personnel", "termination": "90 days notice, no fee", "governing_law": "Federal laws of Canada", "risk_assessment": "Very high security requirements — Top Secret for all 6+ personnel severely limits talent pool. 99.99% SLA on Tier 1 is extremely demanding (allows only 4.3 minutes downtime per month). Ensure Provider has demonstrated capability at this level."}}'
    },
    {
        "instruction": "Extract key metadata fields from this consulting services contract. Return JSON with entity_information, financials_scope, and legal_risk.",
        "input": "PROFESSIONAL SERVICES AGREEMENT between City of Toronto ('Client') and StrategyFirst Consulting LLP ('Consultant'). Engagement: Digital Transformation Strategy. Period: March 1, 2025 to August 31, 2025 (6 months). Basis of Payment: Time and materials. Per Diem Rates: Partner $2,800; Senior Consultant $1,950; Consultant $1,400; Analyst $950. Ceiling Price: $850,000 CAD (not to exceed). Expenses: At cost, no markup, per City travel policy. Invoicing: Monthly, Net 30. Deliverables: Current State Assessment (Apr 30), Jurisdictional Scan (May 31), Strategy Report (Jul 31), Implementation Roadmap (Aug 31). Acceptance: 10 business days. Limitation of Liability: 1x total fees paid. Professional Liability Insurance: $2,000,000. Conflict of Interest: Consultant shall not advise competing municipalities for 12 months. Governing Law: Ontario.",
        "response": '{"entity_information": {"parties": {"purchaser": "City of Toronto (Client)", "supplier": "StrategyFirst Consulting LLP (Consultant)"}, "effective_date": "2025-03-01", "end_date": "2025-08-31", "duration": "6 months"}, "financials_scope": {"pricing_model": "Time and materials with ceiling", "ceiling_price": 850000, "currency": "CAD", "per_diem_rates": {"partner": 2800, "senior_consultant": 1950, "consultant": 1400, "analyst": 950}, "expenses": "At cost, no markup, per City travel policy", "payment_terms": "Monthly, Net 30", "deliverables": [{"name": "Current State Assessment", "due": "2025-04-30"}, {"name": "Jurisdictional Scan", "due": "2025-05-31"}, {"name": "Strategy Report", "due": "2025-07-31"}, {"name": "Implementation Roadmap", "due": "2025-08-31"}], "acceptance_period": "10 business days"}, "legal_risk": {"limitation_of_liability": {"cap": "1x total fees paid (max $850,000)", "assessment": "Standard for consulting — acceptable"}, "insurance": {"professional_liability": "$2,000,000"}, "conflict_of_interest": "Cannot advise competing municipalities for 12 months", "governing_law": "Ontario", "risk_assessment": "Medium — T&M with ceiling shifts cost risk to Consultant if scope grows. Ensure scope is well-defined to avoid hitting ceiling prematurely. The 12-month non-compete for municipalities is broad — verify enforceability."}}'
    },
    {
        "instruction": "Extract key metadata fields from this software license agreement. Return JSON with entity_information, financials_scope, and legal_risk.",
        "input": "SOFTWARE LICENSE AND SUPPORT AGREEMENT between Government of Alberta ('Licensee') and DataVault Software Corp ('Licensor'). Software: DataVault Enterprise v8.0 (perpetual license). License Fee: $1,200,000 CAD (one-time). Annual Maintenance & Support: $240,000 CAD (20% of license fee), payable annually in advance. First Year Free. Support Hours: 24/7 for Severity 1, business hours for Severity 2-3. Response Times: Sev 1: 1 hour; Sev 2: 4 hours; Sev 3: 1 business day. Patches: Critical within 48 hours. Users: Unlimited within the Government of Alberta. Data Residency: Canadian data centres only. Source Code Escrow: NCC Group, release on insolvency or failure to maintain. Limitation of Liability: Greater of $2,000,000 or total fees paid in 24 months. Warranty: 12 months from acceptance. Governing Law: Alberta.",
        "response": '{"entity_information": {"parties": {"purchaser": "Government of Alberta (Licensee)", "supplier": "DataVault Software Corp (Licensor)"}, "license_type": "Perpetual", "software": "DataVault Enterprise v8.0"}, "financials_scope": {"license_fee": 1200000, "annual_maintenance": 240000, "maintenance_percentage": "20% of license fee", "first_year_maintenance": "Included (free)", "currency": "CAD", "total_year_1": 1200000, "total_5_year_cost": 2160000, "users": "Unlimited within Government of Alberta", "support_hours": "24/7 for Severity 1, business hours for Sev 2-3", "response_times": {"severity_1": "1 hour", "severity_2": "4 hours", "severity_3": "1 business day"}, "critical_patches": "Within 48 hours"}, "legal_risk": {"limitation_of_liability": {"cap": "Greater of $2,000,000 or 24 months total fees", "assessment": "Strong — floor of $2M protects against low-payment-period claims"}, "warranty": "12 months from acceptance", "data_residency": "Canadian data centres only", "source_code_escrow": {"agent": "NCC Group", "release_triggers": "Insolvency or failure to maintain"}, "governing_law": "Alberta", "risk_assessment": "Low-Medium — perpetual license is favorable. Source code escrow provides good protection. Verify escrow agreement is current and tested. Monitor 20% annual maintenance — industry standard is 18-22%. Negotiate most-favored-customer pricing on maintenance increases."}}'
    },
]

PROCUREMENT_PROCESS_TRAINING_DATA = [
    {
        "instruction": "Explain the procurement process flow from RFQ to contract execution for a Canadian federal IT services procurement.",
        "input": "",
        "response": '{"process_steps": [{"step": 1, "name": "Requirements Definition", "description": "The client department defines the business need, prepares a Statement of Requirements, conducts market research, and determines the procurement strategy (competitive vs. sole-source). An Algorithmic Impact Assessment may be required for AI systems.", "key_documents": ["Statement of Requirements", "Procurement Plan", "Security Requirements Check List (SRCL)"]}, {"step": 2, "name": "RFQ/RFP Preparation", "description": "PSPC or the department prepares the solicitation document including: evaluation criteria (mandatory and rated), Statement of Work, Basis of Payment, security requirements, and all applicable SACC clauses. Trade agreement coverage is determined based on estimated value.", "key_documents": ["RFP/RFQ", "Statement of Work (SOW)", "Evaluation Criteria", "Draft Contract"]}, {"step": 3, "name": "Solicitation & Bid Period", "description": "The solicitation is published on CanadaBuys (buyandsell.gc.ca). Minimum bid period is 25 days for CFTA-covered procurements, 40 days for CETA/WTO GPA. An industry day or Q&A period may be held. All amendments are published.", "key_documents": ["Published RFP", "Amendment(s)", "Q&A Document"]}, {"step": 4, "name": "Bid Evaluation", "description": "Bids are evaluated in sequence: (1) Administrative compliance check; (2) Mandatory requirements pass/fail; (3) Rated technical criteria scored against published weights; (4) Financial evaluation of compliant bids. The evaluation is conducted by a team including technical evaluators and the contracting authority.", "key_documents": ["Evaluation Matrix", "Consensus Scoring Sheets", "Price Analysis"]}, {"step": 5, "name": "Contract Award", "description": "The contract is awarded to the highest-scoring compliant bidder. A regret letter is sent to unsuccessful bidders with an offer of debriefing. The award notice is published within 72 days. A 10-day standstill period applies for CETA-covered procurements.", "key_documents": ["Award Letter", "Regret Letters", "Contract", "Award Notice"]}, {"step": 6, "name": "Contract Execution & Management", "description": "The contract is executed by both parties. A kick-off meeting is held. The Project Authority manages day-to-day performance. The Contracting Authority manages contract amendments, payments, and compliance. Performance is monitored against SLAs and deliverable milestones.", "key_documents": ["Signed Contract", "Project Charter", "Progress Reports", "Invoices"]}]}'
    },
]
