"""
Advanced training data — Part 6: Insurance requirements training.
Risk-to-coverage mapping, threshold logic, and endorsement requirements.
"""

# ── Risk Scenario → Insurance Requirement Pairs ──────────────

INSURANCE_RISK_MAPPING_TRAINING = [
    {
        "instruction": "Determine the insurance requirements for this scope of work. Return JSON with required policies, limits, endorsements, and rationale.",
        "input": "A consultant providing strategic financial advisory services to the Government of Canada. Contract value: $500,000. Duration: 12 months.",
        "output": '{"required_policies": [{"type": "Professional Liability (E&O)", "limit_per_claim": "$2,000,000", "aggregate": "$2,000,000", "rationale": "Financial advice creates risk of economic loss from negligent recommendations. E&O covers claims of professional negligence, errors, or omissions."}, {"type": "Commercial General Liability (CGL)", "limit_per_occurrence": "$2,000,000", "aggregate": "$2,000,000", "rationale": "Standard coverage for bodily injury and property damage. Required for all on-site work at government facilities."}], "endorsements": ["Canada named as Additional Insured on CGL", "Cross-Liability clause", "30-day notice of cancellation to Canada"], "proof_timeline": "Certificate of Insurance within 10 business days of contract award", "threshold_logic": "Contract value $500K → minimum $2M per policy per Treasury Board guidelines"}'
    },
    {
        "instruction": "Determine the insurance requirements for this scope of work. Return JSON with required policies, limits, endorsements, and rationale.",
        "input": "A construction contractor performing bridge rehabilitation on a federal highway. Contract value: $28,000,000. Duration: 18 months. Work involves excavation near a river.",
        "output": '{"required_policies": [{"type": "Commercial General Liability (CGL)", "limit_per_occurrence": "$10,000,000", "aggregate": "$10,000,000", "rationale": "High-value construction with public exposure. $10M required for contracts over $10M per PWGSC guidelines."}, {"type": "Environmental/Pollution Liability", "limit_per_occurrence": "$5,000,000", "aggregate": "$5,000,000", "rationale": "Excavation near water creates pollution risk. Covers sudden and gradual pollution events, remediation costs."}, {"type": "Automobile Liability", "limit_per_occurrence": "$5,000,000", "rationale": "Heavy equipment and vehicles on highway right-of-way."}, {"type": "Builders Risk (Course of Construction)", "limit": "Full replacement value of the project", "rationale": "Covers damage to the work during construction from fire, weather, vandalism, etc."}, {"type": "Workers Compensation", "limit": "Statutory", "rationale": "Mandatory under provincial workers compensation legislation for all construction workers."}], "endorsements": ["Canada named as Additional Insured on CGL and Auto", "Cross-Liability clause on CGL", "Waiver of Subrogation in favour of Canada on Builders Risk", "30-day notice of cancellation to Canada", "Blanket Contractual Liability on CGL"], "proof_timeline": "Certificate of Insurance within 14 calendar days of contract award, before mobilization", "threshold_logic": "Contract value $28M → $10M CGL (contracts >$10M). Pollution liability required due to work near water. Builders Risk at full replacement value per SACC Section 5."}'
    },
    {
        "instruction": "Determine the insurance requirements for this scope of work. Return JSON with required policies, limits, endorsements, and rationale.",
        "input": "A SaaS vendor hosting Protected B government data in Canadian data centres. Contract value: $3,600,000/year. The vendor processes personal information of 500,000+ citizens.",
        "output": '{"required_policies": [{"type": "Cyber Liability / Network Security", "limit_per_claim": "$5,000,000", "aggregate": "$5,000,000", "rationale": "Protected B data + 500K personal records = high breach exposure. Covers data breach response, notification costs, credit monitoring, regulatory fines, and network security liability."}, {"type": "Technology Errors & Omissions", "limit_per_claim": "$5,000,000", "aggregate": "$5,000,000", "rationale": "SaaS platform failures could disrupt government operations. Covers claims of technology failure, service interruption, and software defects."}, {"type": "Commercial General Liability (CGL)", "limit_per_occurrence": "$5,000,000", "aggregate": "$5,000,000", "rationale": "Standard third-party liability coverage."}], "endorsements": ["Canada named as Additional Insured on CGL", "Cyber policy must include first-party AND third-party coverage", "No exclusion for regulatory fines where insurable by law", "Retroactive date no later than contract commencement", "30-day notice of cancellation to Canada"], "proof_timeline": "Certificate of Insurance within 10 business days of contract award", "threshold_logic": "Annual value $3.6M + Protected B data + 500K records → $5M cyber and tech E&O. High data sensitivity justifies limits above standard $2M threshold."}'
    },
    {
        "instruction": "Determine the insurance requirements for this scope of work. Return JSON with required policies, limits, endorsements, and rationale.",
        "input": "A janitorial services company providing cleaning services at a federal office building. Contract value: $85,000/year. 5 cleaning staff on-site daily.",
        "output": '{"required_policies": [{"type": "Commercial General Liability (CGL)", "limit_per_occurrence": "$2,000,000", "aggregate": "$2,000,000", "rationale": "On-site workers create slip/fall and property damage risk. Standard minimum for service contracts."}, {"type": "Workers Compensation", "limit": "Statutory", "rationale": "Mandatory for all employees. Contractor must provide WSIB clearance certificate."}, {"type": "Fidelity Bond / Employee Dishonesty", "limit": "$100,000", "rationale": "Staff have unsupervised access to federal premises after hours. Covers theft by employees."}], "endorsements": ["Canada named as Additional Insured on CGL", "Cross-Liability clause", "30-day notice of cancellation"], "proof_timeline": "Certificate of Insurance within 10 business days of award", "threshold_logic": "Contract value <$100K → $2M CGL minimum. Fidelity bond required due to unsupervised premises access."}'
    },
    {
        "instruction": "Determine the insurance requirements for this scope of work. Return JSON with required policies, limits, endorsements, and rationale.",
        "input": "An architecture firm designing a new federal laboratory. Contract value: $2,100,000. The lab will handle hazardous biological materials (BSL-3).",
        "output": '{"required_policies": [{"type": "Professional Liability (E&O)", "limit_per_claim": "$5,000,000", "aggregate": "$5,000,000", "rationale": "Design errors for a BSL-3 lab could result in catastrophic containment failure. Higher-than-standard E&O limits required due to hazardous use."}, {"type": "Commercial General Liability (CGL)", "limit_per_occurrence": "$5,000,000", "aggregate": "$5,000,000", "rationale": "On-site inspections and potential design liability."}, {"type": "Pollution Liability", "limit_per_occurrence": "$5,000,000", "rationale": "BSL-3 facility design must account for biological containment. Design failure could lead to environmental contamination claims."}], "endorsements": ["Canada named as Additional Insured on CGL", "E&O policy must not exclude biological/chemical hazard design", "Extended reporting period (tail coverage) of 5 years post-completion", "30-day notice of cancellation"], "proof_timeline": "Certificate of Insurance within 10 business days of award", "threshold_logic": "Contract value $2.1M + BSL-3 hazardous facility → $5M E&O and pollution (elevated from standard $2M due to catastrophic risk potential). Tail coverage essential — design defects may not manifest for years."}'
    },
    {
        "instruction": "Determine the insurance requirements for this scope of work. Return JSON with required policies, limits, endorsements, and rationale.",
        "input": "A medical equipment supplier providing MRI machines to 8 hospital sites. Contract value: $25,000,000. Includes installation, training, and 7-year maintenance.",
        "output": '{"required_policies": [{"type": "Commercial General Liability (CGL)", "limit_per_occurrence": "$10,000,000", "aggregate": "$10,000,000", "rationale": "Medical equipment creates patient safety risk. $10M required for contracts over $10M."}, {"type": "Product Liability", "limit_per_occurrence": "$10,000,000", "aggregate": "$10,000,000", "rationale": "MRI equipment malfunction could cause patient injury. Product liability covers claims arising from defective goods."}, {"type": "Professional Liability (E&O)", "limit_per_claim": "$5,000,000", "rationale": "Installation and calibration errors could affect diagnostic accuracy."}, {"type": "Workers Compensation", "limit": "Statutory", "rationale": "Installation technicians on hospital sites."}], "endorsements": ["Canada/Hospital named as Additional Insured on CGL and Product Liability", "Product recall coverage", "Cross-Liability clause", "No MRI/radiation exclusion on CGL", "30-day notice of cancellation"], "proof_timeline": "Certificate of Insurance within 14 days of award", "threshold_logic": "Contract value $25M + medical equipment + patient safety → $10M CGL and product liability. Product recall endorsement critical for medical devices. Coverage must extend through 7-year maintenance period."}'
    },
]

# ── Insurance Threshold Lookup Table Training ────────────────

INSURANCE_THRESHOLD_TRAINING = [
    {
        "instruction": "What are the standard Canadian federal procurement insurance thresholds? Provide the lookup table mapping contract value to required insurance limits.",
        "input": "",
        "output": '{"threshold_table": [{"contract_value": "Under $100,000", "cgl": "$1,000,000 per occurrence", "eo": "$1,000,000 if professional services", "cyber": "Not typically required", "notes": "Minimum coverage for low-value contracts"}, {"contract_value": "$100,000 - $500,000", "cgl": "$2,000,000 per occurrence", "eo": "$2,000,000 if professional services", "cyber": "$1,000,000 if handling data", "notes": "Standard threshold per Treasury Board Guide"}, {"contract_value": "$500,000 - $2,000,000", "cgl": "$2,000,000 - $5,000,000", "eo": "$2,000,000 - $5,000,000", "cyber": "$2,000,000 if handling sensitive data", "notes": "Limits scaled based on risk profile"}, {"contract_value": "$2,000,000 - $10,000,000", "cgl": "$5,000,000", "eo": "$5,000,000", "cyber": "$2,000,000 - $5,000,000", "notes": "Mid-range contracts — assess specific risks"}, {"contract_value": "Over $10,000,000", "cgl": "$10,000,000+", "eo": "$5,000,000 - $10,000,000", "cyber": "$5,000,000+", "notes": "High-value — may require umbrella/excess policy"}], "special_requirements": {"construction": "Builders Risk at full replacement value + Labour & Material Bond", "it_cloud": "Cyber Liability mandatory for any data handling", "hazardous": "Pollution Liability required for environmental risk", "medical": "Product Liability required for medical devices", "aviation_marine": "Aviation/Marine Liability for specialized operations"}, "source": "Treasury Board of Canada Guide to Insurance, PWGSC SACC Section 5(R)"}'
    },
]

# ── Insurance Terminology Training ───────────────────────────

INSURANCE_TERMINOLOGY_TRAINING = [
    {
        "instruction": "Define these insurance terms in the context of Canadian government procurement. Return JSON with each term's definition and practical significance.",
        "input": "Additional Insured, Waiver of Subrogation, Cross-Liability, Certificate of Insurance, Occurrence vs Claims-Made",
        "output": '{"definitions": [{"term": "Additional Insured", "definition": "A party added to the Contractor\'s insurance policy who receives coverage under that policy. In procurement, Canada (the Crown) is named as Additional Insured on the Contractor\'s CGL policy.", "practical_significance": "If a third party sues Canada for something the Contractor caused, the Contractor\'s insurer must defend and indemnify Canada. Without this, Canada would need to claim against the Contractor directly."}, {"term": "Waiver of Subrogation", "definition": "The insurer waives its right to recover (subrogate) against the named party after paying a claim. In procurement, the Contractor\'s insurer waives subrogation rights against Canada.", "practical_significance": "Prevents the Contractor\'s insurer from suing Canada to recover claim payments. Common on Builders Risk policies where both parties have insurable interest."}, {"term": "Cross-Liability", "definition": "A clause treating each insured party as if they had a separate policy. One Additional Insured can claim against another under the same policy.", "practical_significance": "If Canada is injured by the Contractor\'s negligence, Canada can claim under the Contractor\'s CGL even though both are named insureds on the same policy."}, {"term": "Certificate of Insurance (COI)", "definition": "A document issued by the insurer confirming the types of coverage, limits, effective dates, and named insureds. It is evidence of insurance but does NOT confer coverage.", "practical_significance": "Canada requires COIs within 10 business days of contract award as proof of compliance. Always verify the COI matches the contract requirements — check limits, Additional Insured status, and policy dates."}, {"term": "Occurrence vs Claims-Made", "definition": "Occurrence: covers events that happen during the policy period regardless of when the claim is filed. Claims-Made: covers claims filed during the policy period regardless of when the event occurred. Claims-Made requires a retroactive date and extended reporting period (tail).", "practical_significance": "CGL is typically occurrence-based. Professional Liability (E&O) and Cyber are often claims-made. For claims-made policies, always require: (a) retroactive date no later than contract start; (b) tail coverage of 2+ years after contract end."}]}'
    },
]

# ── SACC Insurance Templates Training ────────────────────────

SACC_INSURANCE_TRAINING = [
    {
        "instruction": "What are the standard SACC (Standard Acquisition Clauses and Conditions) insurance requirements for a federal IT services contract? Provide the exact SACC reference and clause language.",
        "input": "IT managed services contract, $1.5M annual value, hosting Protected B data",
        "output": '{"sacc_reference": "SACC Manual Section 5 — Insurance Requirements (R-series)", "applicable_clauses": [{"clause": "R1250D — Commercial General Liability", "text": "The Contractor must obtain Commercial General Liability insurance with a limit of not less than $2,000,000 per occurrence and $2,000,000 in the annual aggregate, inclusive of defence costs. Canada must be named as Additional Insured. The policy must include Cross-Liability and Blanket Contractual Liability."}, {"clause": "R1260D — Professional Liability (E&O)", "text": "The Contractor must obtain Professional Liability (Errors and Omissions) insurance with a limit of not less than $2,000,000 per claim and in the aggregate. The policy must have a retroactive date no later than the commencement date of the Contract. If the policy is claims-made, the Contractor must maintain coverage for at least 2 years after contract completion."}, {"clause": "R1270D — Cyber Liability", "text": "The Contractor must obtain Cyber Liability insurance with a limit of not less than $2,000,000 per claim and in the aggregate, covering: network security liability, privacy liability, data breach response costs, regulatory defence costs, and media liability. The policy must cover both first-party and third-party losses."}], "additional_requirements": {"proof": "Certificate of Insurance within 10 business days of contract award", "cancellation_notice": "30 days written notice to the Contracting Authority", "currency": "All limits in Canadian dollars", "deductible": "Contractor responsible for all deductibles — deductibles must not exceed $50,000 without approval"}, "risk_note": "For Protected B data at $1.5M/year, consider increasing cyber limits to $5M. Standard $2M may be insufficient given data sensitivity and 500K+ potential affected individuals."}'
    },
]

# ── Combined export ──────────────────────────────────────────

ALL_INSURANCE_TRAINING = (
    INSURANCE_RISK_MAPPING_TRAINING
    + INSURANCE_THRESHOLD_TRAINING
    + INSURANCE_TERMINOLOGY_TRAINING
    + SACC_INSURANCE_TRAINING
)
